'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getBrowserSupabase} from '@/lib/supabase/browser';

const STATUS_LABELS:Record<string,string>={received:'Recibida',reviewing:'En revisión',verified:'Verificada',critical:'Crítica',notified:'Notificada',responding:'En atención',resolved:'Resuelta',discarded:'Descartada'};
const CATEGORY_LABELS:Record<string,string>={fire:'Incendio',traffic_accident:'Accidente vehicular',medical:'Emergencia médica',flood:'Inundación / anegamiento',landslide:'Aluvión / derrumbe',earthquake_damage:'Daños por sismo',power_outage:'Corte de energía',electrical_hazard:'Riesgo eléctrico',gas_leak:'Fuga de gas',water_outage:'Corte de agua',fallen_tree:'Árbol / poste caído',missing_person:'Persona desaparecida',maritime:'Emergencia marítima',security:'Riesgo de seguridad',pollution:'Contaminación',other:'Otra emergencia'};
function fmt(v?:string|null){return v?new Date(v).toLocaleString('es-CL'):'—'}
function risks(r:any){return [r.danger_fire?'Fuego/humo':'',r.danger_injured?'Heridos':'',r.danger_trapped?'Atrapados':'',r.danger_electric?'Peligro eléctrico':'',r.road_blocked?'Vía bloqueada':''].filter(Boolean).join(' · ')||'Sin riesgos marcados'}

export default function AdminDashboard(){
 const s=getBrowserSupabase();const [incidents,setIncidents]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[evidence,setEvidence]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[aiRuns,setAiRuns]=useState<any[]>([]),[mail,setMail]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[access,setAccess]=useState<any[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState('');
 async function load(){setLoading(true);const [i,r,e,n,a,m,p,x]=await Promise.all([
  s.from('incidents').select('id,public_code,category,title,severity,status,region,commune,locality,address_approx,reports_count,first_reported_at,last_reported_at,resolved_at,ai_category,ai_severity,ai_confidence,ai_decision,ai_requires_human').order('last_reported_at',{ascending:false}).limit(1000),
  s.from('reports').select('id,incident_id,category,description,region,commune,locality,address_approx,occurred_at,captured_at,received_at,sync_attempts,client_created_offline,danger_fire,danger_injured,danger_trapped,danger_electric,road_blocked,moderation_state,incidents(public_code,title,status,severity)').order('received_at',{ascending:false}).limit(500),
  s.from('evidence').select('id,incident_id,media_type,bytes,status,created_at').order('created_at',{ascending:false}).limit(1000),
  s.from('incident_notifications').select('id,incident_id,organization_name,channel,status,provider_message_id,created_at').order('created_at',{ascending:false}).limit(1000),
  s.from('ai_agent_runs').select('id,incident_id,status,decision,requires_human,confidence,created_at').order('created_at',{ascending:false}).limit(1000),
  s.from('email_delivery_log').select('id,incident_id,kind,recipient,status,provider_message_id,error,created_at').order('created_at',{ascending:false}).limit(1000),
  s.from('profiles').select('user_id,email,role,active,email_notifications_enabled,created_at').order('created_at',{ascending:false}).limit(1000),
  s.from('access_requests').select('id,email,organization,requested_role,status,created_at').order('created_at',{ascending:false}).limit(500)
 ]);setIncidents(i.data||[]);setReports(r.data||[]);setEvidence(e.data||[]);setNotifications(n.data||[]);setAiRuns(a.data||[]);setMail(m.data||[]);setProfiles(p.data||[]);setAccess(x.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const active=incidents.filter(i=>!['resolved','discarded'].includes(i.status)),resolved=incidents.filter(i=>i.status==='resolved'),critical=incidents.filter(i=>i.status==='critical'||Number(i.severity)>=4),pendingAi=incidents.filter(i=>!i.ai_decision&&!['resolved','discarded'].includes(i.status));
 const categoryStats=useMemo(()=>{const c:Record<string,number>={};for(const i of incidents)c[i.category]=(c[i.category]||0)+1;return Object.entries(c).sort((a,b)=>b[1]-a[1])},[incidents]);
 const statusStats=useMemo(()=>{const c:Record<string,number>={};for(const i of incidents)c[i.status]=(c[i.status]||0)+1;return Object.entries(c).sort((a,b)=>b[1]-a[1])},[incidents]);
 const filteredReports=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return reports.slice(0,100);return reports.filter(r=>[r.description,r.category,r.commune,r.locality,r.address_approx,r.incidents?.public_code,r.incidents?.title].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,100)},[reports,query]);
 if(loading)return <div className="ops-page"><div className="ops-toolbar"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Dashboard general</h1></div></div><p style={{padding:24}}>Cargando información administrativa…</p></div>;
 return <div className="ops-page admin-dashboard-page"><div className="ops-toolbar"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Dashboard general</h1></div><div className="agent-process-row"><Link className="btn btn-secondary btn-sm" href="/operaciones/historial">Historial completo</Link><button className="btn btn-primary btn-sm" onClick={load}>Actualizar</button></div></div>
 <div className="admin-kpis"><article><span>Emergencias registradas</span><b>{incidents.length}</b><small>{reports.length} reportes ciudadanos cargados</small></article><article><span>Activas</span><b>{active.length}</b><small>{critical.length} de prioridad alta/crítica</small></article><article><span>Finalizadas</span><b>{resolved.length}</b><small>Conservadas en historial</small></article><article><span>Evidencias</span><b>{evidence.length}</b><small>{evidence.filter(e=>e.media_type==='video').length} videos · {evidence.filter(e=>e.media_type==='image').length} imágenes</small></article><article><span>IA</span><b>{aiRuns.length}</b><small>{pendingAi.length} activas aún sin decisión IA</small></article><article><span>Canalizaciones</span><b>{notifications.length}</b><small>{notifications.filter(n=>n.status==='sent').length} enviadas</small></article><article><span>Correos Resend</span><b>{mail.length}</b><small>{mail.filter(m=>m.status==='failed').length} fallidos</small></article><article><span>Usuarios activos</span><b>{profiles.filter(p=>p.active).length}</b><small>{access.filter(a=>a.status==='pending').length} solicitudes pendientes</small></article></div>
 <div className="admin-dashboard-grid"><section className="panel-card"><div className="section-title-row"><div><h3>Tipos de emergencia</h3><span className="muted tiny">Distribución de todo lo registrado</span></div></div><div className="admin-stat-list">{categoryStats.map(([k,v])=><div key={k}><span>{CATEGORY_LABELS[k]||k}</span><b>{v}</b><i style={{width:`${Math.max(4,Math.round(v/Math.max(1,incidents.length)*100))}%`}}/></div>)}</div></section><section className="panel-card"><div className="section-title-row"><div><h3>Estado operacional</h3><span className="muted tiny">Situación actual e histórica</span></div></div><div className="admin-stat-list">{statusStats.map(([k,v])=><div key={k}><span>{STATUS_LABELS[k]||k}</span><b>{v}</b><i style={{width:`${Math.max(4,Math.round(v/Math.max(1,incidents.length)*100))}%`}}/></div>)}</div></section></div>
 <section className="panel-card admin-incidents-card"><div className="section-title-row"><div><h3>Emergencias recientes</h3><span className="muted tiny">Incidente consolidado, prioridad, estado, IA y cantidad de reportes</span></div><Link href="/operaciones/historial">Ver historial completo</Link></div><div className="table-wrap"><table><thead><tr><th>Código</th><th>Tipo</th><th>Ubicación</th><th>Prioridad</th><th>Estado</th><th>Reportes</th><th>IA</th><th>Última actividad</th></tr></thead><tbody>{incidents.slice(0,50).map(i=><tr key={i.id}><td><Link href={`/operaciones?incident=${encodeURIComponent(i.id)}`}><b>{i.public_code}</b></Link></td><td>{CATEGORY_LABELS[i.category]||i.title||i.category}</td><td>{i.commune||'—'}<small>{i.locality||i.address_approx||''}</small></td><td>P{i.severity}</td><td>{STATUS_LABELS[i.status]||i.status}</td><td>{i.reports_count}</td><td>{i.ai_decision?`${i.ai_category||'clasificada'} · ${i.ai_confidence!=null?Math.round(Number(i.ai_confidence)*100)+'%':'—'}`:'Pendiente'}</td><td>{fmt(i.last_reported_at)}</td></tr>)}</tbody></table></div></section>
 <section className="panel-card admin-reports-card"><div className="section-title-row"><div><h3>Todo lo reportado por ciudadanos</h3><span className="muted tiny">Tipo original, texto, riesgos, ubicación, sincronización y emergencia asociada</span></div><input className="admin-report-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar código, tipo, descripción o localidad"/></div><div className="table-wrap"><table><thead><tr><th>Emergencia</th><th>Tipo reportado</th><th>Descripción</th><th>Ubicación</th><th>Riesgos</th><th>Conexión</th><th>Captura / recepción</th></tr></thead><tbody>{filteredReports.map(r=><tr key={r.id}><td><Link href={`/operaciones?incident=${encodeURIComponent(r.incident_id)}`}><b>{r.incidents?.public_code||'—'}</b></Link><small>{STATUS_LABELS[r.incidents?.status]||r.incidents?.status||''} · P{r.incidents?.severity||'—'}</small></td><td>{CATEGORY_LABELS[r.category]||r.category}</td><td className="admin-description-cell">{r.description||'Sin descripción'}</td><td>{r.commune||'—'}<small>{r.locality||r.address_approx||''}</small></td><td>{risks(r)}</td><td>{r.client_created_offline?'Creado offline':'Online'}<small>{r.sync_attempts?`${r.sync_attempts} reintento(s)`:''}</small></td><td>{fmt(r.captured_at)}<small>Recibido: {fmt(r.received_at)}</small></td></tr>)}</tbody></table></div></section>
 </div>;
}
