'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getBrowserSupabase} from '@/lib/supabase/browser';
import {hourLabel} from '@/lib/emergency-grouping';

const STATUS_LABELS:Record<string,string>={received:'Recibida',reviewing:'En revisión',verified:'Verificada',critical:'Crítica',notified:'Notificada',responding:'En atención',resolved:'Resuelta',discarded:'Descartada'};
const CATEGORY_LABELS:Record<string,string>={fire:'Incendio',traffic_accident:'Accidente vehicular',medical:'Emergencia médica',flood:'Inundación / anegamiento',landslide:'Aluvión / derrumbe',earthquake_damage:'Daños por sismo',power_outage:'Corte de energía',electrical_hazard:'Riesgo eléctrico',gas_leak:'Fuga de gas',water_outage:'Corte de agua',fallen_tree:'Árbol / poste caído',missing_person:'Persona desaparecida',maritime:'Emergencia marítima',security:'Riesgo de seguridad',pollution:'Contaminación',other:'Otra emergencia'};
function fmt(v?:string|null){return v?new Date(v).toLocaleString('es-CL'):'—'}
function risks(r:any){return [r.danger_fire?'Fuego/humo':'',r.danger_injured?'Heridos':'',r.danger_trapped?'Atrapados':'',r.danger_electric?'Peligro eléctrico':'',r.road_blocked?'Vía bloqueada':''].filter(Boolean).join(' · ')||'Sin riesgos marcados'}

type HourStat={hour:string;category:string;count:number};
type Stats={total_incidents:number;active_incidents:number;resolved_incidents:number;critical_incidents:number;total_reports:number;total_evidence:number;image_evidence:number;video_evidence:number;total_ai_runs:number;pending_ai:number;total_notifications:number;sent_notifications:number;total_emails:number;failed_emails:number;active_users:number;pending_access:number;categories:Record<string,number>;statuses:Record<string,number>;hours_24:HourStat[]};
const EMPTY:Stats={total_incidents:0,active_incidents:0,resolved_incidents:0,critical_incidents:0,total_reports:0,total_evidence:0,image_evidence:0,video_evidence:0,total_ai_runs:0,pending_ai:0,total_notifications:0,sent_notifications:0,total_emails:0,failed_emails:0,active_users:0,pending_access:0,categories:{},statuses:{},hours_24:[]};

export default function AdminDashboard(){
 const s=getBrowserSupabase();const [incidents,setIncidents]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[stats,setStats]=useState<Stats>(EMPTY),[loading,setLoading]=useState(true),[query,setQuery]=useState('');
 async function load(){setLoading(true);const [st,i,r]=await Promise.all([
  s.rpc('admin_dashboard_stats'),
  s.from('incidents').select('id,public_code,category,title,severity,status,region,commune,locality,address_approx,reports_count,first_reported_at,last_reported_at,resolved_at,ai_category,ai_severity,ai_confidence,ai_decision,ai_requires_human').order('last_reported_at',{ascending:false}).limit(250),
  s.from('reports').select('id,incident_id,category,description,region,commune,locality,address_approx,occurred_at,captured_at,received_at,sync_attempts,client_created_offline,danger_fire,danger_injured,danger_trapped,danger_electric,road_blocked,moderation_state,incidents(public_code,title,status,severity)').order('received_at',{ascending:false}).limit(500)
 ]);if(st.data)setStats(st.data as Stats);setIncidents(i.data||[]);setReports(r.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const categoryStats=useMemo(()=>Object.entries(stats.categories||{}).sort((a,b)=>b[1]-a[1]),[stats.categories]);
 const statusStats=useMemo(()=>Object.entries(stats.statuses||{}).sort((a,b)=>b[1]-a[1]),[stats.statuses]);
 const hourly=useMemo(()=>{const map=new Map<string,HourStat[]>();for(const row of stats.hours_24||[]){if(!map.has(row.hour))map.set(row.hour,[]);map.get(row.hour)!.push(row)}return [...map.entries()].map(([hour,items])=>({hour,label:hourLabel(hour),total:items.reduce((n,x)=>n+Number(x.count||0),0),items:[...items].sort((a,b)=>Number(b.count)-Number(a.count))}))},[stats.hours_24]);
 const filteredReports=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return reports.slice(0,100);return reports.filter(r=>[r.description,r.category,r.commune,r.locality,r.address_approx,r.incidents?.public_code,r.incidents?.title].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,100)},[reports,query]);
 if(loading)return <div className="ops-page"><div className="ops-toolbar"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Dashboard general</h1></div></div><p style={{padding:24}}>Cargando información administrativa…</p></div>;
 return <div className="ops-page admin-dashboard-page"><div className="ops-toolbar"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Dashboard general</h1></div><div className="agent-process-row"><Link className="btn btn-secondary btn-sm" href="/operaciones/historial">Historial completo</Link><button className="btn btn-primary btn-sm" onClick={load}>Actualizar</button></div></div>
 <div className="admin-kpis"><article><span>Emergencias registradas</span><b>{stats.total_incidents}</b><small>{stats.total_reports} reportes ciudadanos totales</small></article><article><span>Activas</span><b>{stats.active_incidents}</b><small>{stats.critical_incidents} de prioridad alta/crítica</small></article><article><span>Finalizadas</span><b>{stats.resolved_incidents}</b><small>Conservadas en historial</small></article><article><span>Evidencias</span><b>{stats.total_evidence}</b><small>{stats.video_evidence} videos · {stats.image_evidence} imágenes</small></article><article><span>IA</span><b>{stats.total_ai_runs}</b><small>{stats.pending_ai} activas aún sin decisión IA</small></article><article><span>Canalizaciones</span><b>{stats.total_notifications}</b><small>{stats.sent_notifications} enviadas</small></article><article><span>Correos Resend</span><b>{stats.total_emails}</b><small>{stats.failed_emails} fallidos</small></article><article><span>Usuarios activos</span><b>{stats.active_users}</b><small>{stats.pending_access} solicitudes pendientes</small></article></div>
 <section className="panel-card admin-hourly-card"><div className="section-title-row"><div><h3>Distribución por hora · últimas 24 horas</h3><span className="muted tiny">Agrupación calculada en PostgreSQL con horario de Chile; cada hora se separa además por categoría.</span></div></div>{hourly.length===0?<p className="muted">Sin emergencias en las últimas 24 horas.</p>:<div className="admin-hourly-list">{hourly.map((h,index)=><details key={h.hour} open={index<3}><summary><div><b>{h.label}</b><small>{h.total} emergencia(s)</small></div><span>{h.items.length} categoría(s)</span></summary><div className="admin-hourly-categories">{h.items.map(x=><div key={`${h.hour}-${x.category}`}><span>{CATEGORY_LABELS[x.category]||x.category}</span><b>{x.count}</b></div>)}</div></details>)}</div>}</section>
 <div className="admin-dashboard-grid"><section className="panel-card"><div className="section-title-row"><div><h3>Tipos de emergencia</h3><span className="muted tiny">Distribución sobre todos los incidentes registrados</span></div></div><div className="admin-stat-list">{categoryStats.length?categoryStats.map(([k,v])=><div key={k}><span>{CATEGORY_LABELS[k]||k}</span><b>{v}</b><i style={{width:`${Math.max(4,Math.round(v/Math.max(1,stats.total_incidents)*100))}%`}}/></div>):<p className="muted">Sin datos todavía.</p>}</div></section><section className="panel-card"><div className="section-title-row"><div><h3>Estado operacional</h3><span className="muted tiny">Situación actual e histórica</span></div></div><div className="admin-stat-list">{statusStats.length?statusStats.map(([k,v])=><div key={k}><span>{STATUS_LABELS[k]||k}</span><b>{v}</b><i style={{width:`${Math.max(4,Math.round(v/Math.max(1,stats.total_incidents)*100))}%`}}/></div>):<p className="muted">Sin datos todavía.</p>}</div></section></div>
 <section className="panel-card admin-incidents-card"><div className="section-title-row"><div><h3>Emergencias recientes</h3><span className="muted tiny">Incidente consolidado, prioridad, estado, IA y cantidad de reportes</span></div><Link href="/operaciones/historial">Ver historial completo</Link></div><div className="table-wrap"><table><thead><tr><th>Código</th><th>Tipo</th><th>Ubicación</th><th>Prioridad</th><th>Estado</th><th>Reportes</th><th>IA</th><th>Última actividad</th></tr></thead><tbody>{incidents.slice(0,50).map(i=><tr key={i.id}><td><Link href={`/operaciones?incident=${encodeURIComponent(i.id)}`}><b>{i.public_code}</b></Link></td><td>{CATEGORY_LABELS[i.category]||i.title||i.category}</td><td>{i.commune||'—'}<small>{i.locality||i.address_approx||''}</small></td><td>P{i.severity}</td><td>{STATUS_LABELS[i.status]||i.status}</td><td>{i.reports_count}</td><td>{i.ai_decision?`${i.ai_category||'clasificada'} · ${i.ai_confidence!=null?Math.round(Number(i.ai_confidence)*100)+'%':'—'}`:'Pendiente'}</td><td>{fmt(i.last_reported_at)}</td></tr>)}</tbody></table></div></section>
 <section className="panel-card admin-reports-card"><div className="section-title-row"><div><h3>Todo lo reportado por ciudadanos</h3><span className="muted tiny">Vista rápida. El registro completo está organizado por hora y categoría.</span></div><div className="agent-process-row"><input className="admin-report-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar código, tipo, descripción o localidad"/><Link className="btn btn-secondary btn-sm" href="/operaciones/admin/reportes">Registro completo</Link></div></div><div className="table-wrap"><table><thead><tr><th>Emergencia</th><th>Tipo reportado</th><th>Descripción</th><th>Ubicación</th><th>Riesgos</th><th>Conexión</th><th>Captura / recepción</th></tr></thead><tbody>{filteredReports.map(r=><tr key={r.id}><td><Link href={`/operaciones?incident=${encodeURIComponent(r.incident_id)}`}><b>{r.incidents?.public_code||'—'}</b></Link><small>{STATUS_LABELS[r.incidents?.status]||r.incidents?.status||''} · P{r.incidents?.severity||'—'}</small></td><td>{CATEGORY_LABELS[r.category]||r.category}</td><td className="admin-description-cell">{r.description||'Sin descripción'}</td><td>{r.commune||'—'}<small>{r.locality||r.address_approx||''}</small></td><td>{risks(r)}</td><td>{r.client_created_offline?'Creado offline':'Online'}<small>{r.sync_attempts?`${r.sync_attempts} reintento(s)`:''}</small></td><td>{fmt(r.captured_at)}<small>Recibido: {fmt(r.received_at)}</small></td></tr>)}</tbody></table></div></section>
 </div>;
}
