'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getBrowserSupabase} from '@/lib/supabase/browser';
import {groupByHourAndCategory} from '@/lib/emergency-grouping';
const CATS:Record<string,string>={fire:'Incendio',traffic_accident:'Accidente vehicular',medical:'Emergencia médica',flood:'Inundación / anegamiento',landslide:'Aluvión / derrumbe',earthquake_damage:'Daños por sismo',power_outage:'Corte de energía',electrical_hazard:'Riesgo eléctrico',gas_leak:'Fuga de gas',water_outage:'Corte de agua',fallen_tree:'Árbol / poste caído',missing_person:'Persona desaparecida',maritime:'Emergencia marítima',security:'Riesgo de seguridad',pollution:'Contaminación',other:'Otra emergencia'};
const PAGE=50;function fmt(v?:string|null){return v?new Date(v).toLocaleString('es-CL'):'—'}
function risk(r:any){return [r.danger_fire?'Fuego/humo':'',r.danger_injured?'Heridos':'',r.danger_trapped?'Atrapados':'',r.danger_electric?'Eléctrico':'',r.road_blocked?'Vía bloqueada':''].filter(Boolean).join(', ')||'Ninguno marcado'}
export default function AdminReportsRegistry(){const s=getBrowserSupabase();const [rows,setRows]=useState<any[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(0),[category,setCategory]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true);const grouped=useMemo(()=>groupByHourAndCategory(rows,'received_at'),[rows]);
 async function load(next=page){setLoading(true);let query=s.from('reports').select('id,incident_id,category,description,region,commune,locality,address_approx,occurred_at,captured_at,received_at,sync_attempts,client_created_offline,danger_fire,danger_injured,danger_trapped,danger_electric,road_blocked,moderation_state,incidents(public_code,title,status,severity),evidence(id,media_type,status)',{count:'exact'}).order('received_at',{ascending:false}).range(next*PAGE,next*PAGE+PAGE-1);if(category)query=query.eq('category',category);const term=q.trim().replace(/[,%()]/g,' ');if(term)query=query.or(`description.ilike.%${term}%,commune.ilike.%${term}%,locality.ilike.%${term}%,address_approx.ilike.%${term}%`);const {data,count:c}=await query;setRows(data||[]);setCount(c||0);setPage(next);setLoading(false)}
 useEffect(()=>{load(0)},[category]);
 return <div className="ops-page"><div className="ops-toolbar"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Reportes ciudadanos</h1></div><Link className="btn btn-secondary btn-sm" href="/operaciones/admin">Dashboard</Link></div><div className="admin-report-filters"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load(0)}} placeholder="Buscar descripción, comuna, localidad o dirección"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todos los tipos</option>{Object.entries(CATS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="btn btn-primary btn-sm" onClick={()=>load(0)}>Buscar</button><span>{count} reporte(s)</span></div><section className="panel-card admin-reports-registry">{loading?<p>Cargando…</p>:rows.length===0?<p className="muted">No se encontraron reportes.</p>:<div className="admin-report-groups">{grouped.map((hour,hIndex)=><details className="admin-report-hour" key={hour.key} open={hIndex<2}><summary><div><b>{hour.label}</b><small>{hour.count} reporte(s)</small></div><span>Separado por categoría</span></summary>{hour.categories.map(cat=><details className="admin-report-category" key={`${hour.key}-${cat.category}`} open={hIndex===0}><summary><span>{CATS[cat.category]||cat.category}</span><b>{cat.count}</b></summary><div className="admin-report-cards">{cat.rows.map((r:any)=><article key={r.id}><div className="admin-report-card-head"><div><Link href={`/operaciones?incident=${encodeURIComponent(r.incident_id)}`}><b>{r.incidents?.public_code||'Emergencia'}</b></Link><span>{CATS[r.category]||r.category} · P{r.incidents?.severity||'—'} · {r.incidents?.status||'—'}</span></div><small>{fmt(r.received_at)}</small></div><p>{r.description||'Sin descripción entregada.'}</p><dl><div><dt>Ubicación</dt><dd>{r.commune||'—'}{r.locality?` · ${r.locality}`:''}{r.address_approx?` · ${r.address_approx}`:''}</dd></div><div><dt>Riesgos</dt><dd>{risk(r)}</dd></div><div><dt>Capturado</dt><dd>{fmt(r.captured_at)}</dd></div><div><dt>Conectividad</dt><dd>{r.client_created_offline?'Creado offline':'Online'}{r.sync_attempts?` · ${r.sync_attempts} reintento(s)`:''}</dd></div><div><dt>Evidencia</dt><dd>{(r.evidence||[]).length} archivo(s){(r.evidence||[]).length?` · ${(r.evidence||[]).map((x:any)=>x.media_type).join(', ')}`:''}</dd></div><div><dt>ID reporte</dt><dd><code>{r.id}</code></dd></div></dl></article>)}</div></details>)}</details>)}</div>}<div className="admin-pagination"><button className="btn btn-secondary btn-sm" disabled={page===0||loading} onClick={()=>load(page-1)}>Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(count/PAGE))}</span><button className="btn btn-secondary btn-sm" disabled={(page+1)*PAGE>=count||loading} onClick={()=>load(page+1)}>Siguiente</button></div></section></div>}
