'use client';
import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/browser';

type Run={id:string;incident_id:string;decision:string;suggested_category?:string|null;suggested_severity?:number|null;confidence?:number|null;requires_human:boolean;reason?:string|null;recommended_organizations:any;created_at:string;incidents?:any};
type Action={id:string;incident_id:string;action_type:string;status:string;payload:any;error?:string|null;created_at:string};
type Health={checks?:{aiConfigured?:boolean;mailConfigured?:boolean;emergencyGateway?:boolean;supabaseConfigured?:boolean;mailProvider?:string}};
const decisionLabel:Record<string,string>={urgent_human_review:'Revisión urgente',human_review:'Revisión humana',auto_triage:'Triage automático'};
const ACTIVE=['received','reviewing','verified','critical','notified','responding'];
export default function AgentInbox(){
 const s=getBrowserSupabase();const booted=useRef(false);const [runs,setRuns]=useState<Run[]>([]),[actions,setActions]=useState<Action[]>([]),[loading,setLoading]=useState(true),[health,setHealth]=useState<Health|null>(null),[processing,setProcessing]=useState(false),[processState,setProcessState]=useState('');
 async function load(){setLoading(true);const [r,a]=await Promise.all([s.from('ai_agent_runs').select('id,incident_id,decision,suggested_category,suggested_severity,confidence,requires_human,reason,recommended_organizations,created_at,incidents(public_code,category,severity,status,commune,locality,last_reported_at)').order('created_at',{ascending:false}).limit(100),s.from('ai_agent_actions').select('id,incident_id,action_type,status,payload,error,created_at').in('status',['requires_approval','queued','failed']).order('created_at',{ascending:false}).limit(150)]);setRuns((r.data||[]) as any);setActions((a.data||[]) as any);setLoading(false);try{const h=await fetch('/api/health',{cache:'no-store'});setHealth(await h.json())}catch{setHealth(null)}}
 async function processPending(automatic=false){if(processing)return;setProcessing(true);if(!automatic)setProcessState('Buscando emergencias sin analizar…');try{const {data,error}=await s.from('incidents').select('id,public_code').in('status',ACTIVE).is('ai_processed_at',null).order('last_reported_at',{ascending:false}).limit(automatic?3:10);if(error)throw error;const pending=data||[];if(!pending.length){if(!automatic)setProcessState('No hay emergencias pendientes de análisis.');return}let ok=0,failed=0;for(const item of pending){const r=await fetch('/api/staff/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId:item.id})});if(r.ok)ok++;else{failed++;if(r.status===503)break}}setProcessState(`${ok} emergencia(s) analizada(s)${failed?` · ${failed} con error`:''}.`);await load()}catch{setProcessState('No fue posible procesar las emergencias pendientes.')}finally{setProcessing(false)}}
 useEffect(()=>{load();if(!booted.current){booted.current=true;window.setTimeout(()=>processPending(true),900)}const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
 const stats=useMemo(()=>({urgent:runs.filter(x=>x.decision==='urgent_human_review'&&x.incidents?.status!=='resolved').length,human:runs.filter(x=>x.decision==='human_review'&&x.incidents?.status!=='resolved').length,auto:runs.filter(x=>x.decision==='auto_triage').length,problems:actions.filter(x=>x.status==='failed').length}),[runs,actions]);
 const ordered=useMemo(()=>runs.slice().sort((a,b)=>{const score=(x:Run)=>x.decision==='urgent_human_review'?0:x.decision==='human_review'?1:2;return score(a)-score(b)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime()}),[runs]);
 return <div className="ops-page agent-inbox-page"><div className="ops-toolbar"><div><span className="eyebrow">AGENTE OPERATIVO</span><h1>Bandeja del Agente IA</h1></div><div className="agent-process-row"><button className="btn btn-primary btn-sm" disabled={processing} onClick={()=>processPending(false)}>{processing?'Procesando…':'Procesar pendientes'}</button><button className="btn btn-secondary btn-sm" onClick={load}>Actualizar</button></div></div>{processState?<div className="agent-process-state" style={{padding:'8px 18px 0'}}>{processState}</div>:null}
 <div className="agent-health"><span className={health?.checks?.aiConfigured?'ok':'off'}>Gemini {health?.checks?.aiConfigured?'operativo':'sin configurar'}</span><span className={health?.checks?.mailConfigured?'ok':'off'}>Resend {health?.checks?.mailConfigured?'configurado':'sin configurar'}</span><span className={health?.checks?.emergencyGateway?'ok':'off'}>Receptor {health?.checks?.emergencyGateway?'conectado':'sin respuesta'}</span></div>
 <div className="agent-kpis"><article><b>{stats.urgent}</b><span>revisión urgente</span></article><article><b>{stats.human}</b><span>revisión humana</span></article><article><b>{stats.auto}</b><span>triages automáticos</span></article><article><b>{stats.problems}</b><span>acciones fallidas</span></article></div>
 <div className="agent-inbox-grid"><section className="panel-card"><div className="section-title-row"><h3>Casos priorizados</h3><span className="muted tiny">Urgentes → revisión → automáticos</span></div>{loading?<p>Cargando…</p>:ordered.length===0?<p className="muted">Aún no hay ejecuciones del agente. Pulsa “Procesar pendientes” para analizar emergencias anteriores a la activación del agente.</p>:<div className="agent-run-list">{ordered.map(run=><article className={`agent-run ${run.decision}`} key={run.id}><div className="agent-run-head"><div><b>{run.incidents?.public_code||'Incidente'}</b><span>{decisionLabel[run.decision]||run.decision}</span></div><strong>{run.confidence!=null?`${Math.round(Number(run.confidence)*100)}%`:'—'}</strong></div><div className="agent-run-meta"><span>{run.incidents?.commune||'—'}{run.incidents?.locality?` · ${run.incidents.locality}`:''}</span><span>IA: {run.suggested_category||'—'} · P{run.suggested_severity||'—'}</span><span>Actual: P{run.incidents?.severity||'—'} · {run.incidents?.status||'—'}</span></div>{run.reason?<p>{run.reason}</p>:null}{Array.isArray(run.recommended_organizations)&&run.recommended_organizations.length?<div className="agent-org-chips">{run.recommended_organizations.slice(0,6).map((x:string)=><span key={x}>{x}</span>)}</div>:null}<Link className="btn btn-primary btn-sm" href={`/operaciones?incident=${encodeURIComponent(run.incident_id)}`}>Abrir caso</Link></article>)}</div>}</section>
 <section className="panel-card"><div className="section-title-row"><h3>Acciones pendientes</h3><span className="muted tiny">Preavisos, aprobaciones y errores</span></div>{actions.length===0?<p className="muted">Sin acciones pendientes.</p>:<div className="agent-action-list">{actions.map(a=><article key={a.id}><div><b>{a.action_type}</b><span className={`agent-action-status ${a.status}`}>{a.status}</span></div><p>{a.payload?.organization||a.payload?.reason||a.payload?.publicCode||'Acción del agente'}</p>{a.error?<small>{a.error}</small>:null}<Link href={`/operaciones?incident=${encodeURIComponent(a.incident_id)}`}>Revisar caso</Link></article>)}</div>}</section></div>
 </div>
}
