'use client';
import {useEffect,useMemo,useState} from 'react';
import {getBrowserSupabase} from '@/lib/supabase/browser';
export default function EmailNotificationsAdmin(){
 const s=getBrowserSupabase();const [profiles,setProfiles]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]),[state,setState]=useState(''),[health,setHealth]=useState<any>(null);
 async function load(){const [p,l]=await Promise.all([s.from('profiles').select('user_id,email,full_name,organization,role,active,email_notifications_enabled').order('email'),s.from('email_delivery_log').select('*').order('created_at',{ascending:false}).limit(100)]);setProfiles(p.data||[]);setLogs(l.data||[]);try{const r=await fetch('/api/health',{cache:'no-store'});setHealth(await r.json())}catch{setHealth(null)}}
 useEffect(()=>{load()},[]);const enabled=useMemo(()=>profiles.filter(p=>p.active&&p.email_notifications_enabled).length,[profiles]);
 async function toggle(p:any){const {error}=await s.from('profiles').update({email_notifications_enabled:!p.email_notifications_enabled}).eq('user_id',p.user_id);setState(error?error.message:'Preferencia actualizada');if(!error)load()}
 async function test(){setState('Probando Resend…');const r=await fetch('/api/staff/mail-test',{method:'POST'}),j=await r.json().catch(()=>({}));setState(r.ok?`Resend operativo. Correo enviado a ${j.target}${j.providerMessageId?` · ID ${j.providerMessageId}`:''}`:j.error||'Falló Resend');await load()}
 return <div className="ops-page"><div className="ops-toolbar"><div><span className="eyebrow">NOTIFICACIONES</span><h1>Alertas por correo</h1></div><button className="btn btn-primary btn-sm" onClick={test}>Probar Resend</button></div><div className="agent-health"><span className={health?.checks?.mailConfigured?'ok':'off'}>Resend Vercel {health?.checks?.mailConfigured?'configurado':'sin configurar'}</span><span className={health?.checks?.staffEmailBroadcastConfigured?'ok':'off'}>Alertas automáticas {health?.checks?.staffEmailBroadcastConfigured?'activas':'sin configurar en Supabase'}</span><span className="ok">{enabled} destinatario(s)</span></div>{state?<p className="agent-process-state" style={{padding:'8px 18px 0'}}>{state}</p>:null}<div className="email-admin-grid"><section className="panel-card"><h3>Usuarios con cuenta</h3><p className="muted tiny">Las cuentas activas reciben avisos de nuevas emergencias y de hitos importantes. El administrador puede desactivar alertas por usuario.</p><div className="table-wrap"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Organización</th><th>Alertas</th></tr></thead><tbody>{profiles.map(p=><tr key={p.user_id}><td><b>{p.full_name||p.email}</b><small>{p.email}</small></td><td>{p.role}</td><td>{p.organization||'—'}</td><td><button className={`btn btn-sm ${p.active&&p.email_notifications_enabled?'btn-primary':'btn-secondary'}`} disabled={!p.active} onClick={()=>toggle(p)}>{!p.active?'Cuenta inactiva':p.email_notifications_enabled?'Activadas':'Desactivadas'}</button></td></tr>)}</tbody></table></div></section><section className="panel-card"><h3>Entregas automáticas recientes</h3><p className="muted tiny">Registro independiente del proveedor para nuevas emergencias y cambios críticos.</p>{logs.length===0?<p className="muted">Sin entregas registradas.</p>:<div className="email-delivery-list">{logs.map(l=><article key={l.id}><b>{l.recipient}</b><span className={`agent-action-status ${l.status}`}>{l.status}</span><small>{l.kind} · {new Date(l.created_at).toLocaleString('es-CL')}</small>{l.provider_message_id?<code>{l.provider_message_id}</code>:null}{l.error?<p>{l.error}</p>:null}</article>)}</div>}</section></div></div>;
}
