'use client';
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as maplibregl from 'maplibre-gl';
import type { Map as MapLibreMap } from 'maplibre-gl';
import { STATUS_LABEL } from '@/lib/constants';
import type { PublicIncident } from '@/lib/types';

type Mode='public'|'preview'|'staff';
const fallbackStyle:any={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
function categoryLabel(v:string){const map:Record<string,string>={fire:'Incendio',traffic_accident:'Accidente vehicular',medical:'Emergencia médica',flood:'Inundación',landslide:'Aluvión / derrumbe',earthquake_damage:'Daños por sismo',power_outage:'Corte de energía',electrical_hazard:'Riesgo eléctrico',gas_leak:'Fuga de gas',water_outage:'Corte de agua',fallen_tree:'Árbol / poste caído',missing_person:'Persona desaparecida',maritime:'Emergencia marítima',security:'Riesgo de seguridad',pollution:'Contaminación',other:'Otra emergencia'};return map[v]||v}
export default function EmergencyMap({mode='public',onSelect}:{mode?:Mode;onSelect?:(id:string)=>void}){
 const container=useRef<HTMLDivElement|null>(null),mapRef=useRef<MapLibreMap|null>(null);const [incidents,setIncidents]=useState<PublicIncident[]>([]);const [selected,setSelected]=useState<string|null>(null);const [panelOpen,setPanelOpen]=useState(mode!=='preview');const [panelExpanded,setPanelExpanded]=useState(false);const [loading,setLoading]=useState(true);const [mapError,setMapError]=useState(false);const [search,setSearch]=useState('');const [searching,setSearching]=useState(false);const [searchResults,setSearchResults]=useState<any[]>([]);
 const selectedIncident=useMemo(()=>incidents.find(i=>i.id===selected)||null,[incidents,selected]);
 const load=useCallback(async()=>{try{const r=await fetch('/api/public/incidents',{cache:'no-store'});const j=await r.json();if(r.ok&&Array.isArray(j.incidents))setIncidents(mode==='preview'?j.incidents.slice(0,100):j.incidents)}finally{setLoading(false)}},[mode]);
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[load]);
 useEffect(()=>{if(!container.current||mapRef.current)return;const map=new maplibregl.Map({container:container.current,style:process.env.NEXT_PUBLIC_MAP_STYLE_URL||'https://tiles.openfreemap.org/styles/liberty',center:[-70.3975,-23.6509],zoom:mode==='preview'?11:11.5,attributionControl:{compact:true}});map.addControl(new maplibregl.NavigationControl(),'top-right');if(mode!=='preview'){map.addControl(new maplibregl.FullscreenControl(),'top-right');map.addControl(new maplibregl.GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:true,showUserHeading:true}),'top-right');}let swapped=false;map.on('error',()=>{if(swapped)return;swapped=true;setMapError(true);try{map.setStyle(fallbackStyle)}catch{}});mapRef.current=map;return()=>{map.remove();mapRef.current=null}},[mode]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;const geojson:any={type:'FeatureCollection',features:incidents.filter(i=>Number.isFinite(i.latitude)&&Number.isFinite(i.longitude)).map(i=>({type:'Feature',geometry:{type:'Point',coordinates:[i.longitude,i.latitude]},properties:{id:i.id,severity:i.severity,status:i.status,category:i.category}}))};const apply=()=>{if(map.getSource('incidents')){(map.getSource('incidents') as any).setData(geojson);return;}map.addSource('incidents',{type:'geojson',data:geojson,cluster:true,clusterMaxZoom:14,clusterRadius:48});map.addLayer({id:'clusters',type:'circle',source:'incidents',filter:['has','point_count'],paint:{'circle-color':'#d92d20','circle-radius':['step',['get','point_count'],18,10,24,50,30],'circle-stroke-width':3,'circle-stroke-color':'#fff'}});map.addLayer({id:'cluster-count',type:'symbol',source:'incidents',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':13},paint:{'text-color':'#fff'}});map.addLayer({id:'incident-points',type:'circle',source:'incidents',filter:['!',['has','point_count']],paint:{'circle-radius':['interpolate',['linear'],['get','severity'],1,8,5,13],'circle-color':['step',['get','severity'],'#f59e0b',3,'#ef4444',5,'#991b1b'],'circle-stroke-width':3,'circle-stroke-color':'#fff'}});map.on('click','clusters',e=>{const f=map.queryRenderedFeatures(e.point,{layers:['clusters']})[0];const clusterId=f?.properties?.cluster_id;if(clusterId===undefined)return;const source=map.getSource('incidents') as any;source.getClusterExpansionZoom(clusterId,(err:any,zoom:number)=>{if(!err)map.easeTo({center:(f.geometry as any).coordinates,zoom})})});map.on('click','incident-points',e=>{const id=String(e.features?.[0]?.properties?.id||'');if(!id)return;setSelected(id);setPanelOpen(true);onSelect?.(id)});for(const layer of ['clusters','incident-points']){map.on('mouseenter',layer,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',layer,()=>map.getCanvas().style.cursor='')}};if(map.isStyleLoaded())apply();else map.once('load',apply)},[incidents,onSelect]);
 useEffect(()=>{setTimeout(()=>mapRef.current?.resize(),240)},[panelOpen,panelExpanded]);
 async function geocode(e:FormEvent){e.preventDefault();if(search.trim().length<3)return;setSearching(true);try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(search.trim())}`);const j=await r.json();setSearchResults(j.results||[]);if(j.results?.[0]){const x=j.results[0];mapRef.current?.flyTo({center:[Number(x.lon),Number(x.lat)],zoom:16});}}finally{setSearching(false)}}
 function focusIncident(i:PublicIncident){setSelected(i.id);setPanelOpen(true);mapRef.current?.flyTo({center:[i.longitude,i.latitude],zoom:16});onSelect?.(i.id)}
 return <div className={`emergency-map-shell ${mode==='preview'?'preview':''} ${panelOpen?'panel-open':''}`}>
   <div className="map-canvas" ref={container}/>
   {mode!=='preview'?<div className="map-search-wrap"><form className="map-search" onSubmit={geocode}><input value={search} onChange={e=>{setSearch(e.target.value);if(e.target.value.length<3)setSearchResults([])}} placeholder="Buscar calle, dirección o sector"/><button>{searching?'…':'Buscar'}</button></form>{searchResults.length?<div className="map-search-results">{searchResults.map((r,i)=><button key={`${r.lat}-${r.lon}-${i}`} onClick={()=>{mapRef.current?.flyTo({center:[Number(r.lon),Number(r.lat)],zoom:17});setSearchResults([])}}>{r.displayName}</button>)}</div>:null}</div>:null}
   {mode!=='preview'?<button className="panel-toggle" onClick={()=>setPanelOpen(v=>!v)}>{panelOpen?'Ocultar panel':'Mostrar emergencias'}</button>:null}
   {panelOpen&&mode!=='preview'?<aside className={`map-panel ${panelExpanded?'expanded':''}`}>
     <div className="map-panel-head"><div><span className="eyebrow">EMERGENCIAS REGISTRADAS</span><h2>{selectedIncident?selectedIncident.public_code:'Mapa ciudadano'}</h2></div><div className="map-panel-controls"><button className="icon-button" title={panelExpanded?'Reducir panel':'Ampliar panel'} onClick={()=>setPanelExpanded(v=>!v)}>{panelExpanded?'↘':'↗'}</button><button className="icon-button" title="Cerrar panel" onClick={()=>setPanelOpen(false)}>×</button></div></div>
     {selectedIncident?<div className="incident-public-card"><span className={`severity-pill s${selectedIncident.severity}`}>Prioridad {selectedIncident.severity}/5</span><h3>{selectedIncident.title||categoryLabel(selectedIncident.category)}</h3><p>{selectedIncident.public_summary||'Información pública en revisión.'}</p><dl><div><dt>Estado</dt><dd>{STATUS_LABEL[selectedIncident.status]||selectedIncident.status}</dd></div><div><dt>Ubicación</dt><dd>{selectedIncident.address_approx||selectedIncident.locality||selectedIncident.commune||'Coordenadas registradas'}</dd></div><div><dt>Reportes asociados</dt><dd>{selectedIncident.reports_count}</dd></div><div><dt>Última actualización</dt><dd>{new Date(selectedIncident.last_reported_at).toLocaleString('es-CL')}</dd></div></dl><h4>Canalización / notificaciones</h4><div className="notification-list">{selectedIncident.notifications.length?selectedIncident.notifications.map((n,i)=><div key={`${n.organization}-${i}`}><b>{n.organization}</b><span>{n.channel} · {n.status}</span></div>):<span className="muted">Sin notificaciones registradas todavía.</span>}</div><div className="map-card-actions"><button className="btn btn-secondary btn-sm" onClick={()=>mapRef.current?.flyTo({center:[selectedIncident.longitude,selectedIncident.latitude],zoom:17})}>Centrar punto</button><button className="btn btn-secondary btn-sm" onClick={()=>window.open(`https://www.google.com/maps?q=${selectedIncident.latitude},${selectedIncident.longitude}`,'_blank','noopener,noreferrer')}>Abrir en Google Maps</button><button className="text-button" onClick={()=>setSelected(null)}>Volver a la lista</button></div></div>:<div className="incident-list">{loading?<p>Cargando incidentes…</p>:incidents.length===0?<p className="muted">Todavía no hay emergencias públicas registradas.</p>:incidents.slice(0,100).map(i=><button key={i.id} onClick={()=>focusIncident(i)}><span className={`dot s${i.severity}`}></span><div><b>{i.title||categoryLabel(i.category)}</b><small>{i.commune||i.locality||'Ubicación registrada'} · {STATUS_LABEL[i.status]||i.status}</small></div></button>)}</div>}
   </aside>:null}
   {mapError&&mode!=='preview'?<div className="map-fallback-banner">Proveedor principal no disponible. Cartografía de respaldo activada.</div>:null}
 </div>;
}
