'use client';
import { useEffect, useMemo, useState } from 'react';
import { CANONICAL_EMERGENCY_URL, PURPOSE_LABEL, PURPOSE_RANK, type ChannelPurpose } from '@/lib/operational-routing';

type Channel={id?:string;channel_type:string;label?:string|null;value:string;direct_send?:boolean;automation_enabled?:boolean;is_primary?:boolean;verified_at?:string|null;source_url?:string|null;notes?:string|null;purpose?:ChannelPurpose;purpose_rank?:number};
type Org={id:string;name:string;kind:string;commune?:string|null;email?:string|null;phone?:string|null;website?:string|null;radio_frequency?:string|null;source_url?:string|null;verified_at?:string|null;notes?:string|null;channels:Channel[];operational_rank?:number};
type Incident={public_code:string;title?:string|null;category:string;ai_category?:string|null;ai_severity?:number|null;ai_summary?:string|null;ai_confidence?:number|null;ai_reason?:string|null;ai_requires_human?:boolean|null;ai_decision?:string|null;severity:number;status:string;commune?:string|null;locality?:string|null;address_approx?:string|null;latitude?:number|null;longitude?:number|null;public_summary?:string|null;reports_count?:number|null};
type CitizenReport={id:string;category:string;description?:string|null;region?:string|null;commune?:string|null;locality?:string|null;address_approx?:string|null;occurred_at?:string|null;captured_at?:string|null;received_at?:string|null;danger_fire?:boolean;danger_injured?:boolean;danger_trapped?:boolean;danger_electric?:boolean;road_blocked?:boolean;evidence_count?:number};
type RoutingProfile={category?:string;label?:string;reason?:string;dangerFlags?:string[]};
type AgentContext={reportsCount?:number;evidenceCount?:number;dangerFlags?:string[];descriptions?:string[]};
type EmailHistory={id:string;organization_name:string;destination?:string|null;status:string;provider_message_id?:string|null;sent_at?:string|null;created_at:string;failure_reason?:string|null;subject?:string|null;message_text?:string|null;cc_recipients?:string[]};

function normalizeChannels(org:Org){
  const rows=[...(org.channels||[])];
  const has=(t:string,v?:string|null)=>Boolean(v)&&rows.some(c=>c.channel_type===t&&c.value===v);
  if(org.email&&!has('email',org.email))rows.push({channel_type:'email',label:'Correo institucional',value:org.email,direct_send:true,verified_at:org.verified_at,source_url:org.source_url,purpose:'information',purpose_rank:PURPOSE_RANK.information});
  if(org.phone&&!has('phone',org.phone))rows.push({channel_type:'phone',label:'Teléfono institucional',value:org.phone,verified_at:org.verified_at,source_url:org.source_url,purpose:'information',purpose_rank:PURPOSE_RANK.information});
  if(org.website&&!has('web',org.website))rows.push({channel_type:'web',label:'Sitio web',value:org.website,verified_at:org.verified_at,source_url:org.source_url,purpose:'information',purpose_rank:PURPOSE_RANK.information});
  if(org.radio_frequency&&!has('radio',org.radio_frequency))rows.push({channel_type:'radio',label:'Frecuencia radial',value:org.radio_frequency,verified_at:org.verified_at,source_url:org.source_url,purpose:'information',purpose_rank:PURPOSE_RANK.information});
  return rows.map(c=>({...c,purpose:c.purpose||'information',purpose_rank:c.purpose_rank??PURPOSE_RANK[c.purpose||'information']})).sort((a,b)=>(a.purpose_rank??9)-(b.purpose_rank??9)||Number(Boolean(b.is_primary))-Number(Boolean(a.is_primary)));
}
function actionLabel(type:string){return type==='email'?'Preparar correo':type==='phone'?'Llamar':type==='whatsapp'?'Abrir WhatsApp':type==='telegram'?'Abrir Telegram':type==='facebook'?'Abrir Facebook':type==='instagram'?'Abrir Instagram':type==='x'?'Abrir X':type==='web'?'Abrir sitio':type==='radio'?'Registrar aviso por radio':type==='zello'?'Abrir Zello':type==='sms'?'Registrar SMS':'Registrar contacto'}
function hrefFor(type:string,value:string){const v=value.trim();if(type==='phone')return `tel:${v.replace(/[^+\d*#]/g,'')}`;if(type==='whatsapp'){const n=v.replace(/\D/g,'');return n?`https://wa.me/${n}`:null}if(type==='telegram'){if(/^https:\/\/t\.me\/[A-Za-z0-9_+/-]+$/i.test(v))return v;if(/^@[A-Za-z0-9_]{5,}$/i.test(v))return `https://t.me/${v.slice(1)}`;return null}if(['facebook','instagram','x','web','zello'].includes(type)&&/^https?:\/\//i.test(v))return v;return null}
function dateLabel(value?:string|null){if(!value)return 'Sin fecha';try{return new Date(value).toLocaleDateString('es-CL')}catch{return 'Sin fecha'}}
function dateTimeLabel(value?:string|null){if(!value)return 'No indicada';try{return new Date(value).toLocaleString('es-CL',{dateStyle:'short',timeStyle:'medium'})}catch{return 'No indicada'}}
function statusLabel(value:string){const labels:Record<string,string>={received:'Recibido',reviewing:'En revisión',verified:'Verificado',critical:'Crítico',notified:'Notificado',responding:'En respuesta',resolved:'Resuelto',discarded:'Descartado'};return labels[value]||value}
function yesNo(value?:boolean){return value?'Sí':'No'}
function reportRisks(r:CitizenReport){return `Fuego / humo: ${yesNo(r.danger_fire)}\nPersonas heridas: ${yesNo(r.danger_injured)}\nPersonas atrapadas: ${yesNo(r.danger_trapped)}\nPeligro eléctrico: ${yesNo(r.danger_electric)}\nVía bloqueada: ${yesNo(r.road_blocked)}`}
function reportBlock(r:CitizenReport,index:number){const description=(r.description||'Sin descripción escrita.').trim().slice(0,900);return `REPORTE CIUDADANO ${index+1}\nFecha de envío: ${dateTimeLabel(r.received_at||r.captured_at)}\nFecha indicada del hecho: ${dateTimeLabel(r.occurred_at)}\nRegión: ${r.region||'No indicada'}\nComuna: ${r.commune||'No indicada'}\nSector / localidad: ${r.locality||'No indicada'}\nDirección / referencia: ${r.address_approx||'No indicada'}\nDescripción original:\n${description}\nRiesgos declarados:\n${reportRisks(r)}\nEvidencia asociada: ${r.evidence_count??0} archivo(s)`}
function defaultDraft(i:Incident,orgName:string,reports:CitizenReport[],routing:RoutingProfile|null,ctx:AgentContext|null){
 const first=reports[0]||null;
 const type=i.title||i.category;
 const level=i.severity>=4?'ALERTA':i.severity===3?'AVISO PRIORITARIO':'AVISO INFORMATIVO';
 const subject=`[${level} P${i.severity}] ${i.public_code} · ${type} · ${first?.commune||i.commune||'Ubicación por confirmar'}`;
 const gps=Number.isFinite(Number(i.latitude))&&Number.isFinite(Number(i.longitude))?`${Number(i.latitude).toFixed(6)}, ${Number(i.longitude).toFixed(6)}`:'No disponible';
 const mapsUrl=gps!=='No disponible'?`https://www.google.com/maps?q=${Number(i.latitude).toFixed(6)},${Number(i.longitude).toFixed(6)}`:'No disponible';
 const selectedReports=reports.slice(0,10);
 const reportText=selectedReports.length?selectedReports.map(reportBlock).join('\n\n----------------------------------------\n\n'):'No fue posible recuperar el detalle del formulario ciudadano.';
 const omitted=Math.max(0,reports.length-selectedReports.length);
 const ai=i.ai_summary?`ANÁLISIS DE APOYO DE INNOVA EMERGENCY\nCategoría sugerida: ${i.ai_category||'No disponible'}\nPrioridad sugerida: ${i.ai_severity??'—'}/5\nConfianza: ${i.ai_confidence!=null?`${Math.round(Number(i.ai_confidence)*100)}%`:'—'}\nRevisión humana: ${i.ai_requires_human?'Sí':'No'}\nResumen IA: ${i.ai_summary}\nMotivo: ${i.ai_reason||'No indicado'}\n\nEste análisis es apoyo de triage y no constituye verificación oficial del hecho.`:'ANÁLISIS DE APOYO DE INNOVA EMERGENCY\nAún no existe un análisis IA disponible para este incidente.';
 const routeInfo=routing?`CRITERIO DE DERIVACIÓN OPERATIVA\nPerfil: ${routing.label||routing.category||'No determinado'}\nMotivo: ${routing.reason||'No indicado'}\nRiesgos consolidados: ${(routing.dangerFlags||[]).join(', ')||'Ninguno marcado'}`:'';
 let message=`Estimados/as equipo de ${orgName}:\n\nJunto con saludar, Innova Emergency informa la recepción de uno o más reportes ciudadanos relacionados con una posible situación de emergencia. Se remiten los antecedentes disponibles para su conocimiento, evaluación y, si corresponde, derivación al área operativa competente.\n\nDATOS OPERATIVOS DEL INCIDENTE\nCódigo de emergencia: ${i.public_code}\nTipo actual: ${type}\nPrioridad actual: ${i.severity}/5\nEstado: ${statusLabel(i.status)}\nReportes ciudadanos asociados: ${reports.length||i.reports_count||1}\nEvidencias registradas: ${ctx?.evidenceCount??reports.reduce((n,r)=>n+(r.evidence_count||0),0)} archivo(s)\nComuna: ${first?.commune||i.commune||'No indicada'}\nSector / localidad: ${first?.locality||i.locality||'No indicada'}\nDirección / referencia: ${first?.address_approx||i.address_approx||'No indicada'}\nGPS: ${gps}\nMapa: ${mapsUrl}\n\n${routeInfo}\n\n${ai}\n\nINFORMACIÓN INGRESADA POR LA CIUDADANÍA\n\n${reportText}${omitted?`\n\nHay ${omitted} reporte(s) adicional(es) asociados que pueden revisarse en la plataforma.`:''}\n\nSEGUIMIENTO DEL INCIDENTE\n${CANONICAL_EMERGENCY_URL}\n\nEste mensaje corresponde a la canalización de información proporcionada por ciudadanos. Innova Emergency no certifica por sí sola la veracidad del hecho y esta comunicación no constituye una orden oficial de despacho.\n\nPara una emergencia inmediata deben utilizarse también los canales oficiales que correspondan al hecho: 130 CONAF, 131 SAMU, 132 Bomberos, 133 Carabineros, 134 PDI, 137 emergencias marítimas y otros canales operativos oficiales aplicables.\n\nAtentamente,\nInnova Emergency\nInnova Space Education\ncontacto@innova-space-edu.cl`;
 if(message.length>7800)message=`${message.slice(0,7450)}\n\n[Contenido abreviado por longitud. El detalle completo permanece disponible en Innova Emergency.]\n\nSeguimiento: ${CANONICAL_EMERGENCY_URL}\n\nAtentamente,\nInnova Emergency\nInnova Space Education\ncontacto@innova-space-edu.cl`;
 return {subject,message};
}

export default function IncidentRouting({incidentId,onChanged}:{incidentId:string;onChanged?:()=>void}){
  const [orgs,setOrgs]=useState<Org[]>([]),[selected,setSelected]=useState(''),[scope,setScope]=useState(''),[location,setLocation]=useState(''),[state,setState]=useState(''),[loading,setLoading]=useState(true);
  const [incident,setIncident]=useState<Incident|null>(null),[citizenReports,setCitizenReports]=useState<CitizenReport[]>([]),[routingProfile,setRoutingProfile]=useState<RoutingProfile|null>(null),[agentContext,setAgentContext]=useState<AgentContext|null>(null),[operatorEmail,setOperatorEmail]=useState(''),[adminEmail,setAdminEmail]=useState(''),[emailHistory,setEmailHistory]=useState<EmailHistory[]>([]);
  const [emailChannel,setEmailChannel]=useState<Channel|null>(null),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[lastSentId,setLastSentId]=useState('');
  async function load(){setLoading(true);try{const r=await fetch(`/api/staff/incidents/${incidentId}/routing-options`,{cache:'no-store'}),j=await r.json();if(r.ok){setOrgs(j.organizations||[]);setScope(j.scope||'');setLocation(j.locality||j.commune||'');setSelected(current=>current&&(j.organizations||[]).some((o:Org)=>o.id===current)?current:(j.organizations||[])[0]?.id||'');setIncident(j.incident||null);setCitizenReports(j.citizenReports||[j.citizenReport].filter(Boolean));setRoutingProfile(j.routingProfile||null);setAgentContext(j.agentContext||null);setOperatorEmail(j.operatorEmail||'');setAdminEmail(j.adminEmail||'');setEmailHistory(j.emailHistory||[])}else setState(j.error||'No fue posible cargar contactos.')}catch{setState('No fue posible cargar contactos.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[incidentId]);
  useEffect(()=>{setEmailChannel(null);setSubject('');setMessage('');setLastSentId('')},[selected,incidentId]);
  const org=useMemo(()=>orgs.find(o=>o.id===selected)||null,[orgs,selected]);
  const channels=useMemo(()=>org?normalizeChannels(org):[],[org]);
  const hasMessaging=channels.some(c=>c.channel_type==='whatsapp'||c.channel_type==='telegram');
  function prepareEmail(ch:Channel){if(!org||!incident)return;const draft=defaultDraft(incident,org.name,citizenReports,routingProfile,agentContext);setEmailChannel(ch);setSubject(draft.subject);setMessage(draft.message);setLastSentId('');const p=ch.purpose||'information';setState(PURPOSE_RANK[p]<=PURPOSE_RANK.operations?'Correo preparado para un canal operativo verificado. Revisa antes de enviar.':'Correo preparado como coordinación/escalamiento. Este destino no equivale a una central de despacho.');}
  async function registerChannel(ch:Channel){if(!org)return;const href=hrefFor(ch.channel_type,ch.value);if((ch.channel_type==='whatsapp'||ch.channel_type==='telegram')&&!href){setState(`${actionLabel(ch.channel_type)} no se abrió porque el identificador no tiene un formato verificable.`);return}setState('Registrando canal…');if(href)window.open(href,'_blank','noopener,noreferrer');const r=await fetch('/api/staff/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId,organizationId:org.id,organizationName:org.name,channel:ch.channel_type,destination:ch.value})});const j=await r.json().catch(()=>({}));if(!r.ok){setState(j.error||'No fue posible registrar el contacto.');return}setState(`${actionLabel(ch.channel_type)} abierto/registrado. Falta confirmación manual de recepción.`);onChanged?.()}
  async function sendEmail(){if(!org||!emailChannel)return;setSending(true);setState('Enviando mediante Resend…');const r=await fetch('/api/staff/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId,organizationId:org.id,organizationName:org.name,channel:'email',destination:emailChannel.value,subject,messageText:message})});const j=await r.json().catch(()=>({}));setSending(false);if(!r.ok){setState(j.error||'No fue posible enviar el correo.');return}if(j.notification?.status==='sent'){const id=j.notification.provider_message_id||'registrado';setLastSentId(id);setEmailHistory(h=>[j.notification,...h].slice(0,10));setState(`Correo enviado a ${org.name}. ID Resend: ${id}.`);onChanged?.()}else{if(j.notification)setEmailHistory(h=>[j.notification,...h].slice(0,10));setState(`El correo falló: ${j.notification?.failure_reason||'revisa la configuración de Resend'}.`)}}
  return <section className="detail-section incident-routing">
    <div className="section-title-row"><div><h4>Canalizar / notificar</h4><small className="muted">{scope==='locality'?`Contactos con cobertura en ${location}`:`Respaldo por comuna: ${location}`}</small></div><a className="text-button" href="/operaciones/directorio">Directorio territorial</a></div>
    {routingProfile?<div className="routing-contact-card"><div><b>Criterio operativo</b><span>{routingProfile.label||routingProfile.category}</span></div><p>{routingProfile.reason}</p><small className="muted">Riesgos consolidados: {(routingProfile.dangerFlags||[]).join(', ')||'ninguno marcado'} · Reportes: {agentContext?.reportsCount??citizenReports.length} · Evidencias: {agentContext?.evidenceCount??0}</small></div>:null}
    {loading?<p className="muted">Buscando contactos territoriales…</p>:orgs.length===0?<div className="alert warning">No hay contactos verificados con cobertura para esta ubicación. Revisa el Directorio territorial.</div>:<><label className="stack-label">Organismo / servicio<select value={selected} onChange={e=>setSelected(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{(o.operational_rank??9)<=2?'⚡ ':''}{o.name}</option>)}</select></label>{org?<><div className="routing-contact-card"><div><b>{org.name}</b><span>{org.kind} · {org.commune||'regional'}</span></div>{org.notes?<p>{org.notes}</p>:null}<div className="routing-contact-meta"><span>Última verificación: <b>{dateLabel(org.verified_at)}</b></span>{org.source_url?<a href={org.source_url} target="_blank" rel="noreferrer">Ver fuente</a>:<span>Fuente no registrada</span>}</div></div><div className="routing-channel-grid">{channels.length?channels.map((ch,i)=>{const purpose=ch.purpose||'information';return <button key={`${ch.channel_type}-${ch.value}-${i}`} type="button" className={`btn ${ch.channel_type==='email'?'btn-primary':'btn-secondary'}`} onClick={()=>ch.channel_type==='email'?prepareEmail(ch):registerChannel(ch)}><span>{ch.label||actionLabel(ch.channel_type)}</span><small>{ch.value}</small><small>{PURPOSE_LABEL[purpose]}{ch.verified_at?` · verificado ${dateLabel(ch.verified_at)}`:''}</small></button>}):<p className="muted">Este contacto no tiene canales verificados.</p>}</div>{!hasMessaging?<small className="muted">No hay WhatsApp ni Telegram oficial verificado para este organismo. Innova Emergency no genera números o usuarios por inferencia.</small>:null}</>:null}</>}
    {emailChannel&&org?<div className={`email-composer ${lastSentId?'sent':''}`}><div className="email-composer-head"><div><span className="eyebrow">CORREO A AUTORIDAD / ORGANISMO</span><h4>{lastSentId?'Correo enviado · contenido archivado':'Revisar antes de enviar'}</h4></div><button className="icon-button" type="button" onClick={()=>setEmailChannel(null)}>×</button></div>{lastSentId?<div className="alert success">Envío confirmado por Resend · ID: <b>{lastSentId}</b></div>:null}{emailChannel.purpose&&PURPOSE_RANK[emailChannel.purpose]>PURPOSE_RANK.operations?<div className="alert warning">Este correo está clasificado como <b>{PURPOSE_LABEL[emailChannel.purpose]}</b>. Enviarlo no equivale a activar una central operativa.</div>:null}<div className="email-meta-grid"><div><b>Para</b><span>{emailChannel.value}</span></div><div><b>Copia</b><span>{adminEmail||'Administrador'}</span></div><div><b>Responder a</b><span>{operatorEmail||'Tu correo institucional'}</span></div><div><b>Seguimiento</b><span>{CANONICAL_EMERGENCY_URL}</span></div></div><label>Asunto<input value={subject} maxLength={180} readOnly={Boolean(lastSentId)} onChange={e=>setSubject(e.target.value)}/></label><label>Mensaje<textarea rows={22} value={message} maxLength={8000} readOnly={Boolean(lastSentId)} onChange={e=>setMessage(e.target.value)}/></label><div className="email-composer-actions"><button className="btn btn-secondary" type="button" onClick={()=>setEmailChannel(null)}>Cerrar</button>{!lastSentId?<button className="btn btn-primary" type="button" disabled={sending||!subject.trim()||!message.trim()} onClick={sendEmail}>{sending?'Enviando…':'Enviar correo ahora'}</button>:<button className="btn btn-primary" type="button" onClick={()=>prepareEmail(emailChannel)}>Preparar otro envío</button>}</div><small className="muted">El correo incorpora información ciudadana consolidada, riesgos, evidencia, ubicación, enlace de mapa y análisis de apoyo IA. El contenido enviado queda archivado para auditoría.</small></div>:null}
    {emailHistory.length?<div className="incident-email-history"><div className="section-title-row"><h4>Correos enviados / intentados</h4><small className="muted">Últimos {emailHistory.length}</small></div>{emailHistory.map(mail=><details key={mail.id}><summary><div><b>{mail.organization_name}</b><span>{mail.destination||'Sin destinatario'}</span></div><strong className={`mail-status ${mail.status}`}>{mail.status}</strong></summary><div className="incident-email-audit"><div><b>Fecha</b><span>{new Date(mail.sent_at||mail.created_at).toLocaleString('es-CL')}</span></div><div><b>ID Resend</b><span>{mail.provider_message_id||'—'}</span></div><div><b>Copia</b><span>{mail.cc_recipients?.join(', ')||'—'}</span></div><div className="full"><b>Asunto</b><span>{mail.subject||'—'}</span></div><div className="full"><b>Contenido enviado</b><pre>{mail.message_text||'No registrado en versiones anteriores.'}</pre></div>{mail.failure_reason?<div className="full alert danger">{mail.failure_reason}</div>:null}</div></details>)}</div>:null}
    {state?<p className="muted tiny routing-state">{state}</p>:null}
  </section>
}
