'use client';
import { useEffect, useMemo, useState } from 'react';

type Channel={id?:string;channel_type:string;label?:string|null;value:string;direct_send?:boolean;verified_at?:string|null;source_url?:string|null;notes?:string|null};
type Org={id:string;name:string;kind:string;commune:string;email?:string|null;phone?:string|null;website?:string|null;radio_frequency?:string|null;source_url?:string|null;verified_at?:string|null;notes?:string|null;channels:Channel[]};
type Incident={public_code:string;title?:string|null;category:string;severity:number;status:string;commune?:string|null;locality?:string|null;address_approx?:string|null;latitude?:number|null;longitude?:number|null;public_summary?:string|null};
type EmailHistory={id:string;organization_name:string;destination?:string|null;status:string;provider_message_id?:string|null;sent_at?:string|null;created_at:string;failure_reason?:string|null;subject?:string|null;message_text?:string|null;cc_recipients?:string[]};

function normalizeChannels(org:Org){
  const rows=[...(org.channels||[])];
  const has=(t:string,v?:string|null)=>Boolean(v)&&rows.some(c=>c.channel_type===t&&c.value===v);
  if(org.email&&!has('email',org.email))rows.push({channel_type:'email',label:'Correo',value:org.email,direct_send:true,verified_at:org.verified_at,source_url:org.source_url});
  if(org.phone&&!has('phone',org.phone))rows.push({channel_type:'phone',label:'Teléfono',value:org.phone,verified_at:org.verified_at,source_url:org.source_url});
  if(org.website&&!has('web',org.website))rows.push({channel_type:'web',label:'Sitio web',value:org.website,verified_at:org.verified_at,source_url:org.source_url});
  if(org.radio_frequency&&!has('radio',org.radio_frequency))rows.push({channel_type:'radio',label:'Frecuencia radial',value:org.radio_frequency,verified_at:org.verified_at,source_url:org.source_url});
  return rows;
}
function actionLabel(type:string){return type==='email'?'Preparar correo':type==='phone'?'Llamar':type==='whatsapp'?'Abrir WhatsApp':type==='facebook'?'Abrir Facebook':type==='instagram'?'Abrir Instagram':type==='x'?'Abrir X':type==='web'?'Abrir sitio':type==='radio'?'Registrar aviso por radio':type==='zello'?'Abrir Zello':type==='sms'?'Registrar SMS':'Registrar contacto'}
function hrefFor(type:string,value:string){const v=value.trim();if(type==='phone')return `tel:${v.replace(/[^+\d*#]/g,'')}`;if(type==='whatsapp')return `https://wa.me/${v.replace(/\D/g,'')}`;if(['facebook','instagram','x','web'].includes(type)&&/^https?:\/\//i.test(v))return v;return null}
function dateLabel(value?:string|null){if(!value)return 'Sin fecha';try{return new Date(value).toLocaleDateString('es-CL')}catch{return 'Sin fecha'}}
function defaultDraft(i:Incident,orgName:string){
 const subject=`Alerta informativa ${i.public_code} — Innova Emergency`;
 const message=`Innova Emergency canaliza un reporte ciudadano a ${orgName}.\n\nCódigo: ${i.public_code}\nTipo: ${i.title||i.category}\nPrioridad: ${i.severity}/5\nEstado: ${i.status}\nComuna: ${i.commune||'No indicada'}\nLocalidad: ${i.locality||'No indicada'}\nReferencia: ${i.address_approx||'Ubicación registrada'}\nGPS: ${i.latitude ?? '—'}, ${i.longitude ?? '—'}\nResumen: ${i.public_summary||'En revisión'}\n\nEsta comunicación canaliza información ciudadana y no confirma la veracidad del hecho ni constituye una orden de despacho. Innova Emergency complementa los canales oficiales y no reemplaza 131 SAMU, 132 Bomberos, 133 Carabineros ni SAE/SENAPRED.`;
 return {subject,message};
}

export default function IncidentRouting({incidentId,onChanged}:{incidentId:string;onChanged?:()=>void}){
  const [orgs,setOrgs]=useState<Org[]>([]),[selected,setSelected]=useState(''),[scope,setScope]=useState(''),[location,setLocation]=useState(''),[state,setState]=useState(''),[loading,setLoading]=useState(true);
  const [incident,setIncident]=useState<Incident|null>(null),[operatorEmail,setOperatorEmail]=useState(''),[adminEmail,setAdminEmail]=useState(''),[emailHistory,setEmailHistory]=useState<EmailHistory[]>([]);
  const [emailChannel,setEmailChannel]=useState<Channel|null>(null),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[lastSentId,setLastSentId]=useState('');
  async function load(){setLoading(true);try{const r=await fetch(`/api/staff/incidents/${incidentId}/routing-options`,{cache:'no-store'}),j=await r.json();if(r.ok){setOrgs(j.organizations||[]);setScope(j.scope||'');setLocation(j.locality||j.commune||'');setSelected(current=>current&&(j.organizations||[]).some((o:Org)=>o.id===current)?current:(j.organizations||[])[0]?.id||'');setIncident(j.incident||null);setOperatorEmail(j.operatorEmail||'');setAdminEmail(j.adminEmail||'');setEmailHistory(j.emailHistory||[])}else setState(j.error||'No fue posible cargar contactos.')}catch{setState('No fue posible cargar contactos.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[incidentId]);
  useEffect(()=>{setEmailChannel(null);setSubject('');setMessage('');setLastSentId('')},[selected,incidentId]);
  const org=useMemo(()=>orgs.find(o=>o.id===selected)||null,[orgs,selected]);
  const channels=useMemo(()=>org?normalizeChannels(org):[],[org]);
  function prepareEmail(ch:Channel){if(!org||!incident)return;const draft=defaultDraft(incident,org.name);setEmailChannel(ch);setSubject(draft.subject);setMessage(draft.message);setLastSentId('');setState('Revisa el contenido antes de enviarlo. El destinatario proviene del directorio verificado.');}
  async function registerChannel(ch:Channel){if(!org)return;setState('Registrando canal…');const href=hrefFor(ch.channel_type,ch.value);if(href)window.open(href,'_blank','noopener,noreferrer');const r=await fetch('/api/staff/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId,organizationId:org.id,organizationName:org.name,channel:ch.channel_type,destination:ch.value})});const j=await r.json().catch(()=>({}));if(!r.ok){setState(j.error||'No fue posible registrar el contacto.');return}setState(`${actionLabel(ch.channel_type)} abierto/registrado. Falta confirmación manual de recepción.`);onChanged?.()}
  async function sendEmail(){if(!org||!emailChannel)return;setSending(true);setState('Enviando mediante Resend…');const r=await fetch('/api/staff/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId,organizationId:org.id,organizationName:org.name,channel:'email',destination:emailChannel.value,subject,messageText:message})});const j=await r.json().catch(()=>({}));setSending(false);if(!r.ok){setState(j.error||'No fue posible enviar el correo.');return}if(j.notification?.status==='sent'){const id=j.notification.provider_message_id||'registrado';setLastSentId(id);setEmailHistory(h=>[j.notification,...h].slice(0,10));setState(`Correo enviado a ${org.name}. ID Resend: ${id}.`);onChanged?.()}else{if(j.notification)setEmailHistory(h=>[j.notification,...h].slice(0,10));setState(`El correo falló: ${j.notification?.failure_reason||'revisa la configuración de Resend'}.`)}}
  return <section className="detail-section incident-routing"><div className="section-title-row"><div><h4>Canalizar / notificar</h4><small className="muted">{scope==='locality'?`Contactos con cobertura en ${location}`:`Respaldo por comuna: ${location}`}</small></div><a className="text-button" href="/operaciones/directorio">Directorio territorial</a></div>
    {loading?<p className="muted">Buscando contactos territoriales…</p>:orgs.length===0?<div className="alert warning">No hay contactos verificados con cobertura para esta ubicación. Revisa el Directorio territorial.</div>:<><label className="stack-label">Organismo / radio<select value={selected} onChange={e=>setSelected(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{org?<><div className="routing-contact-card"><div><b>{org.name}</b><span>{org.kind} · {org.commune}</span></div>{org.notes?<p>{org.notes}</p>:null}<div className="routing-contact-meta"><span>Última verificación: <b>{dateLabel(org.verified_at)}</b></span>{org.source_url?<a href={org.source_url} target="_blank" rel="noreferrer">Ver fuente</a>:<span>Fuente no registrada</span>}</div></div><div className="routing-channel-grid">{channels.length?channels.map((ch,i)=><button key={`${ch.channel_type}-${ch.value}-${i}`} type="button" className={`btn ${ch.channel_type==='email'?'btn-primary':'btn-secondary'}`} onClick={()=>ch.channel_type==='email'?prepareEmail(ch):registerChannel(ch)}><span>{ch.label||actionLabel(ch.channel_type)}</span><small>{ch.value}</small>{ch.verified_at?<small>Verificado {dateLabel(ch.verified_at)}</small>:null}</button>):<p className="muted">Este contacto no tiene canales verificados.</p>}</div></>:null}</>}
    {emailChannel&&org?<div className={`email-composer ${lastSentId?'sent':''}`}><div className="email-composer-head"><div><span className="eyebrow">CORREO A AUTORIDAD / ORGANISMO</span><h4>{lastSentId?'Correo enviado · contenido archivado':'Revisar antes de enviar'}</h4></div><button className="icon-button" type="button" onClick={()=>setEmailChannel(null)}>×</button></div>{lastSentId?<div className="alert success">Envío confirmado por Resend · ID: <b>{lastSentId}</b></div>:null}<div className="email-meta-grid"><div><b>Para</b><span>{emailChannel.value}</span></div><div><b>Copia</b><span>{adminEmail||'Administrador'}</span></div><div><b>Responder a</b><span>{operatorEmail||'Tu correo institucional'}</span></div><div><b>Proveedor</b><span>Resend API</span></div></div><label>Asunto<input value={subject} maxLength={180} readOnly={Boolean(lastSentId)} onChange={e=>setSubject(e.target.value)}/></label><label>Mensaje<textarea rows={13} value={message} maxLength={8000} readOnly={Boolean(lastSentId)} onChange={e=>setMessage(e.target.value)}/></label><div className="email-composer-actions"><button className="btn btn-secondary" type="button" onClick={()=>setEmailChannel(null)}>Cerrar</button>{!lastSentId?<button className="btn btn-primary" type="button" disabled={sending||!subject.trim()||!message.trim()} onClick={sendEmail}>{sending?'Enviando…':'Enviar correo ahora'}</button>:<button className="btn btn-primary" type="button" onClick={()=>prepareEmail(emailChannel)}>Preparar otro envío</button>}</div><small className="muted">El asunto, texto, destinatario, copia e ID de Resend quedan registrados para auditoría.</small></div>:null}
    {emailHistory.length?<div className="incident-email-history"><div className="section-title-row"><h4>Correos enviados / intentados</h4><small className="muted">Últimos {emailHistory.length}</small></div>{emailHistory.map(mail=><details key={mail.id}><summary><div><b>{mail.organization_name}</b><span>{mail.destination||'Sin destinatario'}</span></div><strong className={`mail-status ${mail.status}`}>{mail.status}</strong></summary><div className="incident-email-audit"><div><b>Fecha</b><span>{new Date(mail.sent_at||mail.created_at).toLocaleString('es-CL')}</span></div><div><b>ID Resend</b><span>{mail.provider_message_id||'—'}</span></div><div><b>Copia</b><span>{mail.cc_recipients?.join(', ')||'—'}</span></div><div className="full"><b>Asunto</b><span>{mail.subject||'—'}</span></div><div className="full"><b>Contenido enviado</b><pre>{mail.message_text||'No registrado en versiones anteriores.'}</pre></div>{mail.failure_reason?<div className="full alert danger">{mail.failure_reason}</div>:null}</div></details>)}</div>:null}
    {state?<p className="muted tiny routing-state">{state}</p>:null}
  </section>
}
