'use client';
import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import EmergencyMap from '@/components/emergency-map';
import { getBrowserSupabase } from '@/lib/supabase/browser';
import { EMERGENCY_CATEGORIES, STATUS_LABEL } from '@/lib/constants';

type Profile={user_id:string;email:string;full_name?:string|null;organization?:string|null;role:'admin'|'operator'|'authority';active:boolean};
const FLOW_STATUSES=['received','reviewing','verified','critical','notified','responding'];
const decisionLabel:Record<string,string>={auto_triage:'Triage automático',human_review:'Revisión humana',urgent_human_review:'Revisión humana urgente'};

export default function StaffDashboard({profile}:{profile:Profile}){
 const [selected,setSelected]=useState<string|null>(null),[incident,setIncident]=useState<any>(null),[reports,setReports]=useState<any[]>([]),[evidence,setEvidence]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[organizations,setOrganizations]=useState<any[]>([]),[loading,setLoading]=useState(false),[notifyState,setNotifyState]=useState(''),[aiState,setAiState]=useState(''),[statusState,setStatusState]=useState(''),[triageState,setTriageState]=useState(''),[mapVersion,setMapVersion]=useState(0);
 const loadDetail=useCallback(async(id:string)=>{setLoading(true);const s=getBrowserSupabase();const [inc,reps,ev,noti,orgs]=await Promise.all([s.from('incidents').select('*').eq('id',id).single(),s.from('reports').select('*').eq('incident_id',id).order('received_at',{ascending:false}),s.from('evidence').select('*').eq('incident_id',id).order('created_at',{ascending:false}),s.from('incident_notifications').select('*').eq('incident_id',id).order('created_at',{ascending:false}),s.from('organizations').select('*').eq('active',true).order('kind').order('name')]);setIncident(inc.data);setReports(reps.data||[]);setEvidence(ev.data||[]);setNotifications(noti.data||[]);setOrganizations(orgs.data||[]);setLoading(false)},[]);
 useEffect(()=>{if(selected)loadDetail(selected)},[selected,loadDetail]);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('incident');if(id&&/^[0-9a-f-]{36}$/i.test(id))setSelected(id)},[]);
 async function updateStatus(status:string){if(!selected)return;setStatusState('Actualizando estado…');const r=await fetch(`/api/staff/incidents/${selected}/status`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status})});const j=await r.json().catch(()=>({}));if(!r.ok){setStatusState(j.error||'No se pudo actualizar.');return;}setStatusState(status==='resolved'?'Emergencia finalizada y archivada.':'Estado actualizado.');setMapVersion(v=>v+1);if(status==='resolved'||status==='discarded'){setSelected(null);setIncident(null)}else await loadDetail(selected)}
 async function updateTriage(category:string,severity:number){if(!selected)return;setTriageState('Guardando triage…');const r=await fetch(`/api/staff/incidents/${selected}/triage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({category,severity})});const j=await r.json().catch(()=>({}));setTriageState(r.ok?'Categoría y prioridad actualizadas.':j.error||'No se pudo actualizar el triage.');if(r.ok){await loadDetail(selected);setMapVersion(v=>v+1)}}
 async function finalizeIncident(){if(!selected||!incident)return;if(!window.confirm(`¿Finalizar ${incident.public_code}? Saldrá del listado activo y quedará en el historial general.`))return;await updateStatus('resolved')}
 async function updateIncident(patch:any){if(!selected)return;const s=getBrowserSupabase();await s.from('incidents').update(patch).eq('id',selected);await loadDetail(selected);setMapVersion(v=>v+1)}
 async function openEvidence(item:any){const r=await fetch('/api/staff/evidence-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:item.storage_path,evidenceId:item.id})});const j=await r.json();if(r.ok&&j.url)window.open(j.url,'_blank','noopener,noreferrer')}
 async function analyze(){if(!selected)return;setAiState('Analizando texto, señales y evidencia con Gemini…');const r=await fetch('/api/staff/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId:selected})});const j=await r.json().catch(()=>({}));setAiState(r.ok?`Análisis actualizado${j.imagesAnalyzed?` · ${j.imagesAnalyzed} imagen(es) revisadas`:''}.`:j.error||'No se pudo analizar.');if(r.ok)await loadDetail(selected)}
 async function applyAiSuggestion(){if(!incident?.ai_category||!incident?.ai_severity)return;await updateTriage(incident.ai_category,Number(incident.ai_severity))}
 async function sendNotification(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setNotifyState('Enviando…');const f=new FormData(e.currentTarget),orgId=String(f.get('organizationId')||''),org=organizations.find(x=>x.id===orgId),channel=String(f.get('channel')||'email'),destination=String(f.get('destination')||'')||(channel==='email'?org?.email:channel==='radio'?(org?.email||org?.phone):org?.phone)||'';const r=await fetch('/api/staff/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId:selected,organizationId:orgId||null,organizationName:org?.name||String(f.get('organizationName')||'Contacto manual'),channel,destination})});const j=await r.json().catch(()=>({}));setNotifyState(r.ok?'Notificación registrada.':j.error||'No se pudo registrar.');if(r.ok){(e.currentTarget as HTMLFormElement).reset();await loadDetail(selected);setMapVersion(v=>v+1)}}
 const stats=useMemo(()=>({reports:reports.length,evidence:evidence.length,notifications:notifications.length}),[reports,evidence,notifications]);
 const recommendedNames=useMemo(()=>Array.isArray(incident?.ai_recommended_organizations)?incident.ai_recommended_organizations:[],[incident]);
 const relevantOrganizations=useMemo(()=>organizations.slice().sort((a,b)=>{const ar=recommendedNames.includes(a.name)?0:a.commune===incident?.commune?1:2,br=recommendedNames.includes(b.name)?0:b.commune===incident?.commune?1:2;return ar-br||a.name.localeCompare(b.name,'es')}),[organizations,recommendedNames,incident?.commune]);
 return <div className="staff-dashboard">
   <div className="ops-toolbar"><div><span className="eyebrow">CENTRO DE OPERACIONES</span><h1>Emergencias activas</h1></div><div className="ops-toolbar-actions"><Link className="btn btn-secondary btn-sm" href="/operaciones/directorio">Directorio territorial</Link><Link className="btn btn-secondary btn-sm" href="/operaciones/historial">Historial</Link><div className="role-chip">{profile.role}</div></div></div>
   <div className="staff-map-wrap"><EmergencyMap mode="staff" onSelect={setSelected} refreshToken={mapVersion}/></div>
   {selected?<aside className="staff-detail"><div className="staff-detail-head"><div><span className="eyebrow">DETALLE PRIVADO</span><h2>{incident?.public_code||'Cargando…'}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div>{loading?<p>Cargando información completa…</p>:incident?<>
     <div className="staff-summary"><span className={`severity-pill s${incident.severity}`}>Prioridad {incident.severity}/5</span><select value={incident.status} onChange={e=>updateStatus(e.target.value)}>{FLOW_STATUSES.map(v=><option value={v} key={v}>{STATUS_LABEL[v]||v}</option>)}</select></div>
     <section className="triage-controls"><div className="section-title-row"><h4>Triage operativo</h4><span className="muted tiny">Los cambios quedan auditados.</span></div><label>Categoría<select value={incident.category} onChange={e=>updateTriage(e.target.value,Number(incident.severity))}>{EMERGENCY_CATEGORIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Prioridad<select value={incident.severity} onChange={e=>updateTriage(incident.category,Number(e.target.value))}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v}/5</option>)}</select></label><div className="triage-step-buttons"><button className="btn btn-secondary btn-sm" disabled={incident.severity<=1} onClick={()=>updateTriage(incident.category,Math.max(1,Number(incident.severity)-1))}>− Bajar</button><button className="btn btn-danger btn-sm" disabled={incident.severity>=5} onClick={()=>updateTriage(incident.category,Math.min(5,Number(incident.severity)+1))}>＋ Escalar</button></div>{triageState?<small className="muted">{triageState}</small>:null}</section>
     <div className="finalize-row"><button className="btn btn-success" onClick={finalizeIncident}>✓ Finalizar emergencia</button><span>La quitará de emergencias activas y la archivará con fecha de cierre.</span></div>{statusState?<p className="muted tiny">{statusState}</p>:null}
     <h3>{incident.title||incident.category}</h3><p>{incident.description_private||'Sin descripción privada.'}</p>
     <div className="private-grid"><div><b>GPS</b><span>{incident.latitude?.toFixed?.(6)}, {incident.longitude?.toFixed?.(6)}</span></div><div><b>Dirección</b><span>{incident.address_approx||'No indicada'}</span></div><div><b>Reportes</b><span>{stats.reports}</span></div><div><b>Evidencias</b><span>{stats.evidence}</span></div></div>
     <label className="stack-label">Resumen público<textarea rows={3} value={incident.public_summary||''} onChange={e=>setIncident({...incident,public_summary:e.target.value})}/><button className="btn btn-secondary btn-sm" onClick={()=>updateIncident({public_summary:incident.public_summary})}>Guardar resumen público</button></label>
     <section className="detail-section"><div className="section-title-row"><h4>Agente IA</h4><button className="btn btn-secondary btn-sm" onClick={analyze}>Reanalizar con Gemini</button></div>{aiState?<p className="muted tiny">{aiState}</p>:null}{incident.ai_processed_at?<div className={`ai-card ${incident.ai_requires_human?'needs-human':''}`}><div className="ai-decision-row"><b>{decisionLabel[incident.ai_decision]||'Evaluación IA'}</b><span>{incident.ai_requires_human?'Requiere usuario':'Puede manejar triage simple'}</span></div><span>Categoría sugerida: {incident.ai_category} · prioridad {incident.ai_severity}/5 · confianza {incident.ai_confidence!=null?`${Math.round(Number(incident.ai_confidence)*100)}%`:'—'}</span><p>{incident.ai_summary}</p>{incident.ai_reason?<small>{incident.ai_reason}</small>:null}{recommendedNames.length?<div className="ai-recommendations"><b>Derivación sugerida</b>{recommendedNames.map((x:string)=><span key={x}>{x}</span>)}</div>:null}<button className="btn btn-primary btn-sm" onClick={applyAiSuggestion}>Aplicar categoría/prioridad sugerida</button><small>La IA apoya triage y derivación; no confirma autenticidad ni reemplaza una orden oficial de despacho.</small></div>:<p className="muted">El agente automático analizará los reportes nuevos. También puedes ejecutar un análisis manual con evidencia.</p>}</section>
     <section className="detail-section"><h4>Evidencias privadas</h4><div className="evidence-private-grid">{evidence.length?evidence.map(ev=><button key={ev.id} onClick={()=>openEvidence(ev)}><span>{ev.media_type==='video'?'🎥':'📷'}</span><b>{ev.media_type}</b><small>{ev.mime_type}</small></button>):<p className="muted">Sin evidencias.</p>}</div></section>
     <section className="detail-section"><h4>Reportes asociados</h4><div className="report-private-list">{reports.map(r=><article key={r.id}><b>{new Date(r.received_at).toLocaleString('es-CL')}</b><span>{r.description||'Sin descripción'}</span><small>{r.address_approx||r.locality||r.commune||'GPS registrado'}</small></article>)}</div></section>
     <section className="detail-section"><div className="section-title-row"><h4>Canalizar / notificar</h4><Link className="text-button" href="/operaciones/directorio">Ver directorio por localidad</Link></div><form className="notification-form" onSubmit={sendNotification}><select name="organizationId" defaultValue="" required><option value="" disabled>Selecciona organismo o radio</option>{relevantOrganizations.map(o=><option key={o.id} value={o.id}>{recommendedNames.includes(o.name)?'★ ':''}{o.name}{o.kind==='radio'&&o.radio_frequency?` · ${o.radio_frequency}`:''}</option>)}</select><select name="channel" defaultValue="email"><option value="email">Correo</option><option value="radio">Radio / medio</option><option value="web">Publicación web</option><option value="whatsapp">WhatsApp (manual)</option><option value="sms">SMS (manual)</option><option value="manual">Contacto manual</option></select><input name="destination" placeholder="Destino opcional (correo/teléfono)"/><button className="btn btn-primary btn-sm">Registrar / enviar</button></form>{notifyState?<p className="muted tiny">{notifyState}</p>:null}<div className="notification-list">{notifications.length?notifications.map(n=><div key={n.id}><b>{n.organization_name}</b><span>{n.channel} · {n.status}</span></div>):<p className="muted">Sin notificaciones.</p>}</div></section>
   </>:null}</aside>:null}
 </div>;
}
