'use client';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import EmergencyMap from '@/components/emergency-map';
import { getBrowserSupabase } from '@/lib/supabase/browser';
import { STATUS_LABEL } from '@/lib/constants';

type Profile={user_id:string;email:string;full_name?:string|null;organization?:string|null;role:'admin'|'operator'|'authority';active:boolean};
export default function StaffDashboard({profile}:{profile:Profile}){
 const [selected,setSelected]=useState<string|null>(null),[incident,setIncident]=useState<any>(null),[reports,setReports]=useState<any[]>([]),[evidence,setEvidence]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[organizations,setOrganizations]=useState<any[]>([]),[loading,setLoading]=useState(false),[notifyState,setNotifyState]=useState(''),[aiState,setAiState]=useState('');
 const loadDetail=useCallback(async(id:string)=>{setLoading(true);const s=getBrowserSupabase();const [inc,reps,ev,noti,orgs]=await Promise.all([s.from('incidents').select('*').eq('id',id).single(),s.from('reports').select('*').eq('incident_id',id).order('received_at',{ascending:false}),s.from('evidence').select('*').eq('incident_id',id).order('created_at',{ascending:false}),s.from('incident_notifications').select('*').eq('incident_id',id).order('created_at',{ascending:false}),s.from('organizations').select('*').eq('active',true).order('kind').order('name')]);setIncident(inc.data);setReports(reps.data||[]);setEvidence(ev.data||[]);setNotifications(noti.data||[]);setOrganizations(orgs.data||[]);setLoading(false)},[]);
 useEffect(()=>{if(selected)loadDetail(selected)},[selected,loadDetail]);
 async function updateIncident(patch:any){if(!selected)return;const s=getBrowserSupabase();await s.from('incidents').update(patch).eq('id',selected);await loadDetail(selected)}
 async function openEvidence(item:any){const r=await fetch('/api/staff/evidence-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:item.storage_path,evidenceId:item.id})});const j=await r.json();if(r.ok&&j.url)window.open(j.url,'_blank','noopener,noreferrer')}
 async function analyze(){if(!selected)return;setAiState('Analizando con Gemini…');const r=await fetch('/api/staff/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId:selected})});const j=await r.json().catch(()=>({}));setAiState(r.ok?'Análisis actualizado.':j.error||'No se pudo analizar.');if(r.ok)await loadDetail(selected)}
 async function sendNotification(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setNotifyState('Enviando…');const f=new FormData(e.currentTarget),orgId=String(f.get('organizationId')||''),org=organizations.find(x=>x.id===orgId),channel=String(f.get('channel')||'email'),destination=String(f.get('destination')||'')||(channel==='email'?org?.email:channel==='radio'?(org?.email||org?.phone):org?.phone)||'';const r=await fetch('/api/staff/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({incidentId:selected,organizationId:orgId||null,organizationName:org?.name||String(f.get('organizationName')||'Contacto manual'),channel,destination})});const j=await r.json().catch(()=>({}));setNotifyState(r.ok?'Notificación registrada.':j.error||'No se pudo registrar.');if(r.ok){(e.currentTarget as HTMLFormElement).reset();await loadDetail(selected)}}
 const stats=useMemo(()=>({reports:reports.length,evidence:evidence.length,notifications:notifications.length}),[reports,evidence,notifications]);
 return <div className="staff-dashboard">
   <div className="ops-toolbar"><div><span className="eyebrow">CENTRO DE OPERACIONES</span><h1>Emergencias en tiempo real</h1></div><div className="role-chip">{profile.role}</div></div>
   <div className="staff-map-wrap"><EmergencyMap mode="staff" onSelect={setSelected}/></div>
   {selected?<aside className="staff-detail"><div className="staff-detail-head"><div><span className="eyebrow">DETALLE PRIVADO</span><h2>{incident?.public_code||'Cargando…'}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div>{loading?<p>Cargando información completa…</p>:incident?<>
     <div className="staff-summary"><span className={`severity-pill s${incident.severity}`}>Prioridad {incident.severity}/5</span><select value={incident.status} onChange={e=>updateIncident({status:e.target.value,resolved_at:e.target.value==='resolved'?new Date().toISOString():null})}>{Object.entries(STATUS_LABEL).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div>
     <h3>{incident.title||incident.category}</h3><p>{incident.description_private||'Sin descripción privada.'}</p>
     <div className="private-grid"><div><b>GPS</b><span>{incident.latitude?.toFixed?.(6)}, {incident.longitude?.toFixed?.(6)}</span></div><div><b>Dirección</b><span>{incident.address_approx||'No indicada'}</span></div><div><b>Reportes</b><span>{stats.reports}</span></div><div><b>Evidencias</b><span>{stats.evidence}</span></div></div>
     <label className="stack-label">Resumen público<textarea rows={3} value={incident.public_summary||''} onChange={e=>setIncident({...incident,public_summary:e.target.value})}/><button className="btn btn-secondary btn-sm" onClick={()=>updateIncident({public_summary:incident.public_summary})}>Guardar resumen público</button></label>
     <section className="detail-section"><div className="section-title-row"><h4>Análisis IA</h4><button className="btn btn-secondary btn-sm" onClick={analyze}>Analizar con Gemini</button></div>{aiState?<p className="muted tiny">{aiState}</p>:null}{incident.ai_processed_at?<div className="ai-card"><b>{incident.ai_category}</b><span>Severidad sugerida: {incident.ai_severity}/5 · confianza {incident.ai_confidence ?? '—'}</span><p>{incident.ai_summary}</p><small>Es una sugerencia de apoyo; no constituye verificación ni orden de despacho.</small></div>:<p className="muted">La plataforma aplicó priorización conservadora. El análisis Gemini aparecerá cuando su API esté configurada.</p>}</section>
     <section className="detail-section"><h4>Evidencias privadas</h4><div className="evidence-private-grid">{evidence.length?evidence.map(ev=><button key={ev.id} onClick={()=>openEvidence(ev)}><span>{ev.media_type==='video'?'🎥':'📷'}</span><b>{ev.media_type}</b><small>{ev.mime_type}</small></button>):<p className="muted">Sin evidencias.</p>}</div></section>
     <section className="detail-section"><h4>Reportes asociados</h4><div className="report-private-list">{reports.map(r=><article key={r.id}><b>{new Date(r.received_at).toLocaleString('es-CL')}</b><span>{r.description||'Sin descripción'}</span><small>{r.address_approx||r.locality||r.commune||'GPS registrado'}</small></article>)}</div></section>
     <section className="detail-section"><h4>Canalizar / notificar</h4><form className="notification-form" onSubmit={sendNotification}><select name="organizationId" defaultValue="" required><option value="" disabled>Selecciona organismo o radio</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}{o.kind==='radio'&&o.radio_frequency?` · ${o.radio_frequency}`:''}</option>)}</select><select name="channel" defaultValue="email"><option value="email">Correo</option><option value="radio">Radio / medio</option><option value="web">Publicación web</option><option value="whatsapp">WhatsApp (registro/manual)</option><option value="sms">SMS (registro/manual)</option><option value="manual">Contacto manual</option></select><input name="destination" placeholder="Destino opcional (correo/teléfono)"/><button className="btn btn-primary btn-sm">Registrar / enviar</button></form>{notifyState?<p className="muted tiny">{notifyState}</p>:null}<div className="notification-list">{notifications.length?notifications.map(n=><div key={n.id}><b>{n.organization_name}</b><span>{n.channel} · {n.status}</span></div>):<p className="muted">Sin notificaciones.</p>}</div></section>
   </>:null}</aside>:null}
 </div>;
}
