'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/browser';

type Locality={id:string;region:string;province?:string|null;commune:string;locality:string;locality_type:string};
type Channel={id:string;organization_id:string;channel_type:string;label?:string|null;value:string;direct_send:boolean;automation_enabled:boolean;is_primary:boolean;source_url?:string|null;verified_at?:string|null;notes?:string|null};
type Org={id:string;name:string;kind:string;region:string;commune:string;email?:string|null;phone?:string|null;website?:string|null;radio_frequency?:string|null;source_url?:string|null;verified_at?:string|null;notes?:string|null;active:boolean;channels:Channel[];coverage:string[]};
type Policy={id:string;region:string;commune?:string|null;auto_triage_enabled:boolean;min_confidence_auto:number;max_severity_auto:number;auto_prealert_enabled:boolean;allowed_channel_types:string[];active:boolean};
const KINDS=[['radio','Radio / medio'],['municipality','Municipalidad'],['emergency_management','Gestión de emergencias'],['fire','Bomberos'],['medical','Salud'],['police','Seguridad'],['electricity','Electricidad'],['other','Otro']];
const CHANNELS=[['email','Correo'],['phone','Teléfono'],['whatsapp','WhatsApp'],['facebook','Facebook'],['instagram','Instagram'],['x','X / Twitter'],['web','Web'],['radio','Frecuencia radial'],['zello','Zello'],['sms','SMS'],['other','Otro']];
const kindLabel=(v:string)=>KINDS.find(x=>x[0]===v)?.[1]||v;
const channelLabel=(v:string)=>CHANNELS.find(x=>x[0]===v)?.[1]||v;
function hrefFor(c:Channel){const v=c.value.trim();if(c.channel_type==='email')return `mailto:${v}`;if(c.channel_type==='phone')return `tel:${v.replace(/[^+\d]/g,'')}`;if(c.channel_type==='whatsapp')return `https://wa.me/${v.replace(/\D/g,'')}`;if(['facebook','instagram','x','web'].includes(c.channel_type)&&/^https?:\/\//i.test(v))return v;return null}

export default function TerritorialDirectory({canEdit}:{canEdit:boolean}){
 const s=getBrowserSupabase();const [orgs,setOrgs]=useState<Org[]>([]),[localities,setLocalities]=useState<Locality[]>([]),[policy,setPolicy]=useState<Policy|null>(null),[commune,setCommune]=useState(''),[locality,setLocality]=useState(''),[kind,setKind]=useState(''),[editing,setEditing]=useState(''),[formCommune,setFormCommune]=useState('Antofagasta');
 async function load(){const [o,c,cov,l,p]=await Promise.all([s.from('organizations').select('*').eq('active',true).eq('region','Antofagasta').order('commune').order('kind').order('name'),s.from('organization_channels').select('*').eq('active',true).order('is_primary',{ascending:false}),s.from('organization_coverage').select('organization_id,locality_id').eq('active',true),s.from('territorial_localities').select('*').eq('active',true).eq('region','Antofagasta').order('commune').order('locality'),s.from('ai_agent_policies').select('*').eq('region','Antofagasta').is('commune',null).maybeSingle()]);const channels=(c.data||[]) as Channel[],coverage=cov.data||[];setLocalities((l.data||[]) as Locality[]);setPolicy(p.data as Policy|null);setOrgs((o.data||[]).map((x:any)=>({...x,channels:channels.filter(ch=>ch.organization_id===x.id),coverage:coverage.filter((y:any)=>y.organization_id===x.id).map((y:any)=>y.locality_id)})))}
 useEffect(()=>{load()},[]);
 const communes=useMemo(()=>Array.from(new Set(localities.map(x=>x.commune))).sort((a,b)=>a.localeCompare(b,'es')),[localities]);
 const locOptions=useMemo(()=>localities.filter(x=>!commune||x.commune===commune),[localities,commune]);
 const formLocs=useMemo(()=>localities.filter(x=>x.commune===formCommune),[localities,formCommune]);
 const filtered=useMemo(()=>orgs.filter(o=>(!kind||o.kind===kind)&&(!commune||o.commune===commune||o.coverage.some(id=>localities.find(x=>x.id===id)?.commune===commune))&&(!locality||o.coverage.includes(locality))),[orgs,kind,commune,locality,localities]);
 async function toggleChannel(ch:Channel){if(!canEdit)return;setEditing(ch.id);await s.from('organization_channels').update({automation_enabled:!ch.automation_enabled,updated_at:new Date().toISOString()}).eq('id',ch.id);await load();setEditing('')}
 async function updatePolicy(patch:Partial<Policy>){if(!canEdit||!policy)return;setEditing('policy');await s.from('ai_agent_policies').update({...patch,updated_at:new Date().toISOString()}).eq('id',policy.id);await load();setEditing('')}
 async function addContact(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canEdit)return;setEditing('add');const f=new FormData(e.currentTarget),name=String(f.get('name')||'').trim(),comm=String(f.get('commune')||''),localityId=String(f.get('localityId')||''),kindValue=String(f.get('kind')||'other'),channelType=String(f.get('channelType')||'email'),value=String(f.get('value')||'').trim(),source=String(f.get('sourceUrl')||'').trim()||null,notes=String(f.get('notes')||'').trim()||null;if(!name||!comm||!value){setEditing('');return}
 let {data:org}=await s.from('organizations').select('*').eq('name',name).eq('commune',comm).maybeSingle();if(!org){const {data,error}=await s.from('organizations').insert({name,kind:kindValue,region:'Antofagasta',commune:comm,active:true,source_url:source,verified_at:new Date().toISOString(),notes}).select('*').single();if(error){alert(error.message);setEditing('');return}org=data}
 const direct=channelType==='email';const {error:chErr}=await s.from('organization_channels').upsert({organization_id:org.id,channel_type:channelType,label:String(f.get('label')||'').trim()||channelLabel(channelType),value,direct_send:direct,automation_enabled:false,is_primary:true,active:true,source_url:source,verified_at:new Date().toISOString(),notes},{onConflict:'organization_id,channel_type,value'});if(chErr){alert(chErr.message);setEditing('');return}
 if(localityId)await s.from('organization_coverage').upsert({organization_id:org.id,locality_id:localityId,priority:10,active:true},{onConflict:'organization_id,locality_id'});else{const ids=localities.filter(x=>x.commune===comm).map(x=>x.id);if(ids.length)await s.from('organization_coverage').upsert(ids.map(id=>({organization_id:org.id,locality_id:id,priority:20,active:true})),{onConflict:'organization_id,locality_id'})}
 (e.currentTarget as HTMLFormElement).reset();setFormCommune('Antofagasta');await load();setEditing('')}
 async function addLocality(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canEdit)return;setEditing('locality');const f=new FormData(e.currentTarget);const {error}=await s.from('territorial_localities').upsert({region:'Antofagasta',commune:String(f.get('commune')),locality:String(f.get('locality')).trim(),locality_type:String(f.get('localityType')||'other'),source_name:'Registro administrador Innova Emergency',source_url:String(f.get('sourceUrl')||'').trim()||null,verified_at:new Date().toISOString(),active:true},{onConflict:'region,commune,locality'});if(error)alert(error.message);else{(e.currentTarget as HTMLFormElement).reset();await load()}setEditing('')}
 return <div className="ops-page directory-page"><div className="ops-toolbar"><div><span className="eyebrow">RED TERRITORIAL</span><h1>Directorio de alertas</h1></div><div className="role-chip">Región de Antofagasta</div></div>
 <div className="panel-card directory-filters"><label>Comuna<select value={commune} onChange={e=>{setCommune(e.target.value);setLocality('')}}><option value="">Todas</option>{communes.map(x=><option key={x}>{x}</option>)}</select></label><label>Localidad<select value={locality} onChange={e=>setLocality(e.target.value)}><option value="">Todas</option>{locOptions.map(x=><option key={x.id} value={x.id}>{x.locality}</option>)}</select></label><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">Todos</option>{KINDS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="directory-count"><b>{filtered.length}</b><span>organizaciones</span></div></div>
 {policy?<section className="panel-card agent-policy-card"><div><span className="eyebrow">AGENTE IA</span><h3>Política de automatización regional</h3><p>El triage simple puede ser automático. Los preavisos solo salen por canales habilitados y nunca sustituyen los canales oficiales.</p></div><div className="agent-policy-controls"><label><span>Triage automático</span><input type="checkbox" checked={policy.auto_triage_enabled} disabled={!canEdit||editing==='policy'} onChange={e=>updatePolicy({auto_triage_enabled:e.target.checked})}/></label><label><span>Preavisos automáticos</span><input type="checkbox" checked={policy.auto_prealert_enabled} disabled={!canEdit||editing==='policy'} onChange={e=>updatePolicy({auto_prealert_enabled:e.target.checked})}/></label><label>Confianza mínima<select value={policy.min_confidence_auto} disabled={!canEdit} onChange={e=>updatePolicy({min_confidence_auto:Number(e.target.value)})}><option value="0.85">85%</option><option value="0.9">90%</option><option value="0.95">95%</option><option value="0.98">98%</option></select></label><label>Máxima prioridad automática<select value={policy.max_severity_auto} disabled={!canEdit} onChange={e=>updatePolicy({max_severity_auto:Number(e.target.value)})}><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label></div></section>:null}
 {canEdit?<details className="panel-card directory-add"><summary>＋ Registrar organización o nuevo canal</summary><form className="directory-form" onSubmit={addContact}><input name="name" placeholder="Organización / radio" required/><select name="kind" defaultValue="radio">{KINDS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select name="commune" value={formCommune} onChange={e=>setFormCommune(e.target.value)}>{communes.map(x=><option key={x}>{x}</option>)}</select><select name="localityId" defaultValue=""><option value="">Toda la comuna</option>{formLocs.map(x=><option key={x.id} value={x.id}>{x.locality}</option>)}</select><select name="channelType" defaultValue="email">{CHANNELS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="label" placeholder="Etiqueta del canal"/><input name="value" placeholder="Correo, teléfono, URL, frecuencia…" required/><input name="sourceUrl" type="url" placeholder="Fuente pública de verificación"/><input name="notes" placeholder="Notas"/><button className="btn btn-primary" disabled={editing==='add'}>{editing==='add'?'Guardando…':'Guardar'}</button></form></details>:null}
 {canEdit?<details className="panel-card directory-add"><summary>＋ Agregar localidad / sector</summary><form className="directory-form locality-form" onSubmit={addLocality}><select name="commune" required>{communes.map(x=><option key={x}>{x}</option>)}</select><input name="locality" placeholder="Localidad / sector" required/><select name="localityType" defaultValue="other"><option value="city">Ciudad</option><option value="town">Pueblo</option><option value="village">Aldea</option><option value="hamlet">Caserío</option><option value="sector">Sector</option><option value="rural">Rural</option><option value="other">Otra</option></select><input name="sourceUrl" type="url" placeholder="Fuente pública"/><button className="btn btn-secondary" disabled={editing==='locality'}>Agregar localidad</button></form></details>:null}
 <div className="directory-cards">{filtered.map(o=><article className="directory-card" key={o.id}><header><div><span>{o.commune}</span><h3>{o.name}</h3></div><b>{kindLabel(o.kind)}</b></header><div className="directory-coverage"><strong>Cobertura</strong><span>{o.coverage.map(id=>localities.find(x=>x.id===id)?.locality).filter(Boolean).join(' · ')||o.commune}</span></div><div className="directory-channels">{o.channels.length?o.channels.map(ch=>{const href=hrefFor(ch);return <div className="directory-channel" key={ch.id}><div><b>{ch.label||channelLabel(ch.channel_type)}</b><span>{ch.value}</span>{ch.verified_at?<small>Verificado {new Date(ch.verified_at).toLocaleDateString('es-CL')}</small>:null}</div><div className="directory-channel-actions">{href?<a className="btn btn-secondary btn-sm" href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer">Abrir</a>:null}{canEdit&&ch.direct_send?<button className={`btn btn-sm ${ch.automation_enabled?'btn-success':'btn-secondary'}`} disabled={editing===ch.id} onClick={()=>toggleChannel(ch)}>{ch.automation_enabled?'IA habilitada':'Habilitar IA'}</button>:null}</div></div>}):<p className="muted">Sin canales verificados.</p>}</div>{o.source_url?<footer><a href={o.source_url} target="_blank" rel="noreferrer">Ver fuente</a>{o.notes?<span>{o.notes}</span>:null}</footer>:null}</article>)}</div>
 </div>
}
