export type AiAssessment={category:string;severity:number;summary:string;confidence:number;recommendedOrganizations:string[];reason:string;needsHumanReview:boolean;inconsistencies:string[]};
export type AiImageInput={mimeType:string;base64:string};

const CATEGORIES=['fire','traffic_accident','medical','flood','landslide','earthquake_damage','power_outage','electrical_hazard','gas_leak','water_outage','fallen_tree','missing_person','maritime','security','pollution','other'] as const;

export async function classifyEmergency(input:{category:string;description:string;dangerFlags:string[];images?:AiImageInput[]}) : Promise<AiAssessment|null> {
  const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return null;
  const model=process.env.GEMINI_MODEL||'gemini-3.6-flash';
  const imageCount=input.images?.length||0;
  const prompt=`Eres el agente de triage de Innova Emergency, una plataforma de canalización ciudadana de emergencias en Chile. Tu salida es SOLO una evaluación técnica estructurada para apoyar a operadores. No confirmes que el hecho sea verdadero, no identifiques personas, no inventes evidencia, no ordenes despachos oficiales y no reemplaces 131, 132, 133 ni SAE/SENAPRED.\n\nClasifica conservadoramente. Distingue entre hechos descritos por el ciudadano y observaciones realmente visibles en las imágenes. Si faltan datos, hay contradicciones, la categoría podría cambiar, la gravedad es alta, existen personas heridas/atrapadas, fuego, riesgo eléctrico o cualquier ambigüedad relevante, marca needsHumanReview=true. La confianza debe reflejar la calidad real de la información.\n\nCategoría declarada: ${input.category}\nDescripción ciudadana: ${input.description||'(sin descripción)'}\nIndicadores marcados por el ciudadano: ${input.dangerFlags.join(', ')||'ninguno'}\nImágenes privadas adjuntas: ${imageCount}\n\nDevuelve: categoría sugerida dentro del catálogo, severidad 1 a 5, resumen factual corto, confianza 0 a 1, tipos u organizaciones recomendadas, razón, si requiere revisión humana y una lista de inconsistencias o dudas. No incluyas nombres de personas.`;
  const parts:any[]=[{text:prompt},...(input.images||[]).map(img=>({inlineData:{mimeType:img.mimeType,data:img.base64}}))];
  const schema={type:'object',properties:{category:{type:'string',enum:[...CATEGORIES]},severity:{type:'integer',minimum:1,maximum:5},summary:{type:'string'},confidence:{type:'number',minimum:0,maximum:1},recommendedOrganizations:{type:'array',items:{type:'string'},maxItems:12},reason:{type:'string'},needsHumanReview:{type:'boolean'},inconsistencies:{type:'array',items:{type:'string'},maxItems:10}},required:['category','severity','summary','confidence','recommendedOrganizations','reason','needsHumanReview','inconsistencies'],additionalProperties:false};
  try{
    const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{parts}],generationConfig:{responseMimeType:'application/json',responseSchema:schema}}),signal:AbortSignal.timeout(45000)});
    if(!response.ok){console.error('Gemini classify failed',response.status,(await response.text()).slice(0,1000));return null}
    const payload=await response.json();const text=payload?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('')||'';
    try{const parsed=JSON.parse(text) as AiAssessment;return {...parsed,severity:Math.min(5,Math.max(1,Number(parsed.severity)||1)),confidence:Math.min(1,Math.max(0,Number(parsed.confidence)||0)),needsHumanReview:Boolean(parsed.needsHumanReview),inconsistencies:Array.isArray(parsed.inconsistencies)?parsed.inconsistencies:[],recommendedOrganizations:Array.isArray(parsed.recommendedOrganizations)?parsed.recommendedOrganizations:[]}}catch{console.error('Gemini returned invalid structured JSON');return null}
  }catch(error){console.error('Gemini classify request failed',error);return null}
}
