import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import {createClient} from 'npm:@supabase/supabase-js@2.111.0';
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}})}
function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern){try{return JSON.parse(modern).default as string}catch{}}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''}
function adminClient(){const url=Deno.env.get('SUPABASE_URL')||'',key=secretKey();if(!url||!key)throw new Error('Supabase server credentials unavailable');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function sha256(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function validUuid(v:unknown){return typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
function validEmail(v:string){return /^\S+@\S+\.\S+$/.test(v)}
function chunks<T>(arr:T[],size:number){const out:T[][]=[];for(let i=0;i<arr.length;i+=size)out.push(arr.slice(i,i+size));return out}
async function resend(args:{to:string[];bcc?:string[];subject:string;text:string;idempotencyKey:string}){const apiKey=Deno.env.get('RESEND_API_KEY')?.trim();const from=(Deno.env.get('EMAIL_FROM')||'Innova Emergency <contacto@innova-space-edu.cl>').trim();if(!apiKey)throw new Error('RESEND_API_KEY no está configurada en Supabase Edge Function Secrets');const payload:any={from,to:args.to,subject:args.subject,text:args.text};if(args.bcc?.length)payload.bcc=args.bcc;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json','Idempotency-Key':args.idempotencyKey.slice(0,256)},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.message||`Resend respondió ${r.status}`);if(!data?.id)throw new Error('Resend no devolvió ID');return String(data.id)}
async function authenticateStaff(sb:any,req:Request){const auth=req.headers.get('authorization')||'';const token=auth.toLowerCase().startsWith('bearer ')?auth.slice(7):'';if(!token)return null;const {data:{user}}=await sb.auth.getUser(token);if(!user)return null;const {data:profile}=await sb.from('profiles').select('user_id,email,role,active').eq('user_id',user.id).maybeSingle();if(!profile?.active)return null;return {user,profile}}
async function reportIncidentId(sb:any,reportId:string,secret:string){const {data:report}=await sb.from('reports').select('incident_id,submission_secret_hash').eq('id',reportId).maybeSingle();if(!report||report.submission_secret_hash!==await sha256(secret))return null;return String(report.incident_id)}
async function broadcast(sb:any,incidentId:string,kind:string,eventLabel:string){const {data:already}=await sb.from('email_delivery_log').select('id').eq('incident_id',incidentId).eq('kind',kind).eq('status','sent').limit(1);if(already?.length)return {alreadyNotified:true,sent:0};const {data:incident,error:incError}=await sb.from('incidents').select('id,public_code,title,category,severity,status,commune,locality,address_approx,public_summary').eq('id',incidentId).single();if(incError||!incident)throw incError||new Error('Incidente no encontrado');const {data:profiles,error:profError}=await sb.from('profiles').select('email,active,email_notifications_enabled').eq('active',true).eq('email_notifications_enabled',true);if(profError)throw profError;const admin=(Deno.env.get('ADMIN_EMAIL')||Deno.env.get('EMAIL_SEND_TO')||'contacto@innova-space-edu.cl').trim().toLowerCase();const staff=[...new Set((profiles||[]).map((p:any)=>String(p.email||'').trim().toLowerCase()).filter(validEmail))];const others=staff.filter((e:string)=>e!==admin);const site=(Deno.env.get('INNOVA_EMERGENCY_URL')||'https://emergencias-4yfs.vercel.app').replace(/\/$/,'');const subject=`[P${incident.severity}] ${eventLabel} ${incident.public_code} — ${incident.commune||'Antofagasta'}`;const text=`${eventLabel} en Innova Emergency.\n\nCódigo: ${incident.public_code}\nTipo: ${incident.title||incident.category}\nPrioridad: ${incident.severity}/5\nEstado: ${incident.status}\nComuna: ${incident.commune||'No indicada'}\nLocalidad/sector: ${incident.locality||'No indicado'}\nReferencia: ${incident.address_approx||'Ubicación registrada'}\nResumen: ${incident.public_summary||'Información en revisión'}\n\nCentro de operaciones: ${site}/operaciones?incident=${incident.id}\n\nLa información debe ser verificada por personal autorizado. Innova Emergency complementa la comunicación y no reemplaza 131, 132, 133 ni SAE/SENAPRED.`;const batches=chunks(others,45);if(!batches.length)batches.push([]);let sentCount=0;for(let i=0;i<batches.length;i++){const batch=batches[i];let to:string[],bcc:string[]|undefined,recipients:string[];if(i===0){to=[admin];bcc=batch;recipients=[admin,...batch]}else{to=[batch[0]];bcc=batch.slice(1);recipients=batch}try{const providerId=await resend({to,bcc,subject,text,idempotencyKey:`${kind}-${incident.id}-${i}`});sentCount+=recipients.length;await sb.from('email_delivery_log').insert(recipients.map(email=>({incident_id:incident.id,kind,recipient:email,provider:'resend',provider_message_id:providerId,status:'sent'})))}catch(error){const message=error instanceof Error?error.message:'Fallo de Resend';await sb.from('email_delivery_log').insert(recipients.map(email=>({incident_id:incident.id,kind,recipient:email,provider:'resend',status:'failed',error:message})));throw error}}return {alreadyNotified:false,sent:sentCount}}
Deno.serve(async(req:Request)=>{if(req.method==='GET')return json({ok:true,provider:'resend',configured:Boolean(Deno.env.get('RESEND_API_KEY')),fromConfigured:Boolean(Deno.env.get('EMAIL_FROM'))});if(req.method!=='POST')return json({error:'Método no permitido'},405);try{const body=await req.json(),mode=String(body.mode||'new-incident'),sb=adminClient();if(mode==='new-incident'){const reportId=String(body.reportId||''),secret=String(body.secret||'');if(!validUuid(reportId)||secret.length<24)return json({error:'Datos inválidos'},400);const incidentId=await reportIncidentId(sb,reportId,secret);if(!incidentId)return json({error:'Credencial de reporte inválida'},403);EdgeRuntime.waitUntil(broadcast(sb,incidentId,'staff_new_incident','Nueva emergencia').catch(e=>console.error('staff new incident email',e)));return json({ok:true,queued:true},202)}if(mode==='staff-event'){const staff=await authenticateStaff(sb,req);if(!staff)return json({error:'No autorizado'},401);const incidentId=String(body.incidentId||''),event=String(body.event||'');if(!validUuid(incidentId)||!['critical','responding','resolved'].includes(event))return json({error:'Evento inválido'},400);const map:any={critical:['staff_critical','Emergencia escalada a crítica'],responding:['staff_responding','Emergencia en atención'],resolved:['staff_resolved','Emergencia finalizada']};const [kind,label]=map[event];EdgeRuntime.waitUntil(broadcast(sb,incidentId,kind,label).catch((e:any)=>console.error('staff event email',e)));return json({ok:true,queued:true,event},202)}return json({error:'Modo inválido'},400)}catch(error){console.error(error);return json({error:'No fue posible iniciar la notificación'},500)}});
