revoke all privileges on table public.profiles,public.incidents,public.reports,public.evidence,public.organizations,public.incident_notifications,public.access_requests,public.audit_log,public.rate_limit_events from authenticated;
grant select,update on public.profiles to authenticated;
grant select,update on public.incidents to authenticated;
grant select,update on public.reports to authenticated;
grant select on public.evidence to authenticated;
grant select,insert,update,delete on public.organizations to authenticated;
grant select,insert,update on public.incident_notifications to authenticated;
grant select,update on public.access_requests to authenticated;
grant select on public.audit_log to authenticated;
drop policy if exists organizations_staff_all on public.organizations;
drop policy if exists organizations_staff_read on public.organizations;
drop policy if exists organizations_admin_write on public.organizations;
create policy organizations_staff_read on public.organizations for select to authenticated using(public.is_staff());
create policy organizations_admin_write on public.organizations for all to authenticated using(public.is_staff(array['admin'::public.app_role])) with check(public.is_staff(array['admin'::public.app_role]));
drop policy if exists notifications_staff_all on public.incident_notifications;
drop policy if exists notifications_staff_read on public.incident_notifications;
drop policy if exists notifications_staff_insert on public.incident_notifications;
drop policy if exists notifications_staff_update on public.incident_notifications;
create policy notifications_staff_read on public.incident_notifications for select to authenticated using(public.is_staff());
create policy notifications_staff_insert on public.incident_notifications for insert to authenticated with check(public.is_staff());
create policy notifications_staff_update on public.incident_notifications for update to authenticated using(public.is_staff()) with check(public.is_staff());
drop policy if exists incidents_staff_all on public.incidents;
drop policy if exists incidents_staff_read on public.incidents;
drop policy if exists incidents_staff_update on public.incidents;
create policy incidents_staff_read on public.incidents for select to authenticated using(public.is_staff());
create policy incidents_staff_update on public.incidents for update to authenticated using(public.is_staff()) with check(public.is_staff());
